# Real-World Data Wrangling

## 1. Gather data

In this section, we will extract data using at least two different data gathering methods and combine the data.

### **1.1.** Problem Statement

How does the streaming revolution compare to traditional theatrical releases in terms of financial performance, audience reception, and content characteristics, and how have these metrics evolved over time when accounting for inflation?

The film industry has undergone a dramatic shift from theatrical dominance to streaming platforms, but how do these distribution channels compare in terms of content characteristics, audience engagement, and financial viability?

This project merges TMDb theatrical movie data, IMDb ratings, four major streaming platform catalogs, and Federal Reserve CPI data to conduct a comprehensive analysis of streaming-exclusive versus theatrical releases. By adjusting all budgets and revenues to 2024 dollars using inflation data, I can fairly compare financial performance across six decades (1960-2024) and determine whether the "streaming revolution" represents truly different content or simply a new distribution channel for similar movies.

The primary data wrangling challenge involves fuzzy matching movies across datasets with inconsistent identifiers, requiring normalized title matching and year-based validation.

### **1.2.** Dataset Overview

This project combines four distinct data sources gathered using three different methods:

| Dataset | Source | Method | Size | Primary Use |
|---------|--------|--------|------|-------------|
| TMDb Movies | Kaggle | Manual Download | 10K movies | Theatrical releases, financial data |
| IMDb Ratings | IMDb Datasets | Programmatic Download | ~50K movies (filtered) | Additional ratings, metadata validation |
| Streaming Platforms | Kaggle | Manual Download | ~22K titles | Streaming availability, exclusive content |
| CPI Inflation Data | FRED API | API Access | 65 years (1960-2024) | Inflation adjustment for financial analysis |

The combination of these datasets enables analysis of streaming versus theatrical releases while ensuring fair financial comparisons across six decades.

In [1]:
# Import statements for packages used in analysis
import httpx
import os
import zlib

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sb

from dotenv import load_dotenv
from pandas.api.types import is_numeric_dtype
from urllib.parse import urlparse

## It's OK if this file doesn't exist as the API results are 
## saved to a file in the project and the API code will check
## for the file before using the API key this would retrieve.
load_dotenv(dotenv_path=f"{os.path.expanduser('~/.env')}")

# Magic word for inline visualizations
%matplotlib inline

# Set default figure size for better readability
sb.set_style('whitegrid')
plt.rcParams['figure.figsize'] = (12, 6)

In [2]:
## Data gathering and display functions
def download_and_save_file(url, local_filename, path="data/raw", download_if_exists=False):
    """
    Downloads a file from a URL and saves it locally.
    By default the file is saved to the data/raw path.
    
    If the file is gzipped, it's decompressed on-the-fly and
    written as uncompressed data.

    Args:
        url (str): URL of file to download.
        local_filename (str): Name of file to save locally.
    """
    filepath = f"{path}/{local_filename}"
    
    if os.path.exists(filepath) and download_if_exists is False:
        print(f"{filepath} already exists. If you wish to re-download it, set download_if_exists=True")
        return
    
    try:
        with httpx.stream("GET", url, headers={"Accept-Encoding": "gzip"}) as response:
            # Raise an exception for bad status codes
            response.raise_for_status()

            headers = response.headers
            is_gzip = False
            
            print(f"Downloading {url} --> {filepath}")

            # Check if response is gzipped
            if 'content-encoding' in headers and 'gzip' in headers['content-encoding']:
                    is_gzip = True

            elif 'content-type' in headers and 'binary/octet-stream' in headers['content-type']:                
                # AWS likes to send this back; just check the extension
                _, extension = os.path.splitext(urlparse(url).path)

                if extension == '.gz':
                    is_gzip = True

            # Decompress file if it's gzipped
            if is_gzip is True:
                print("Decompressing gzip content...")

                decompressor = zlib.decompressobj(wbits=zlib.MAX_WBITS | 16)
                download_size = 0
                count = 0

                with open(filepath, "wb") as outfile:
                    for chunk in response.iter_bytes():
                        count += 1
                        download_size += len(chunk)
                        decompressed_chunk = decompressor.decompress(chunk)

                        if download_size % 1000000 == 0:
                            print(f"Downloaded bytes: {download_size:,}")

                        outfile.write(decompressed_chunk)

                print(f"Downloaded {count:,} chunks for file size {download_size:,}")
                
                remaining_data = decompressor.flush()
                if remaining_data:
                    with open(filepath, "wb") as outfile:
                        outfile.write(remaining_data)


            # If not gzipped, just write raw content to the output file
            else:
                with open(filepath, 'wb') as outfile:
                    for chunk in response.iter_bytes():
                        outfile.write(chunk)

            # Give the user feedback
            print(f"File '{local_filename}' downloaded successfully from '{url}'")

    # Check for various issues
    except httpx.HTTPStatusError as e:
        print(f"HTTP error occurred: {e}")
        
    except httpx.RequestError as e:
        print(f"An error occurred while requesting {url}: {e}")
        
    except IOError as e:
        print(f"Error saving file '{local_filename}': {e}")

def display_shape(df):
    """
    Output rows and columns of dataframe
    """
    print(f"\nRows: {df.shape[0]:,}")
    print(f"Columns: {df.shape[1]:,}\n")

#### TMDb Movies Dataset

The TMDb (The Movie Database) dataset provides comprehensive information about 10,000 theatrical movies, representing the foundation of this analysis. This dataset is particularly valuable because it includes both original and inflation-adjusted financial figures (budget_adj and revenue_adj to 2010 dollars), extensive production metadata, and audience reception metrics. TMDb's community-driven model ensures broad coverage of theatrical releases while maintaining high data quality through active curation.

Source URL: https://www.kaggle.com/datasets/juzershakir/tmdb-movies-dataset

Type: CSV (6.85 MB)

Method: Manual download from Kaggle

**Dataset variables:**
- id (int) - TMDb unique identifier
- imdb_id (string) - IMDb identifier for cross-dataset linking
- popularity (float) - TMDb popularity score
- budget (int) - Production budget in nominal dollars
- revenue (int) - Total box office revenue in nominal dollars
- original_title (string) - Original title
- cast (string) - Cast members (pipe-delimited)
- homepage (string) - Official movie homepage URL
- director (string) - Director name
- tagline (string) - Marketing catchphrase
- keywords (string) - Descriptive keywords (pipe-delimited)
- overview (string) - Plot synopsis
- runtime (int) - Duration in minutes
- genres (string) - Movie genres (pipe-delimited)
- production_companies (string) - Production companies (pipe-delimited)
- release_date (string) - Release date (format: 6/9/2015)
- vote_count (int) - Total number of TMDb user votes
- vote_average (float) - Average TMDb user rating (0-10 scale)
- release_year (int) - Release year
- budget_adj (float) - Budget adjusted to 2010 dollars
- revenue_adj (float) - Revenue adjusted to 2010 dollars

**Why this dataset:**
TMDb serves as the core theatrical release dataset because it combines financial data (budget/revenue), audience reception (ratings/votes), production details (cast/director/companies), and content characteristics (genres/runtime) in a single source. The pre-existing inflation adjustment to 2010 demonstrates awareness of temporal comparison challenges, though this project will re-adjust all figures to 2024 dollars for consistency. The imdb_id field enables precise linking to IMDb data, while the comprehensive metadata supports fuzzy matching to streaming platforms where IDs are absent.

**Significance of variables:**
- **id/imdb_id:** Primary keys for merging with IMDb and tracking across datasets
- **budget/revenue (and _adj versions):** Core financial metrics for profitability analysis; will be re-adjusted to 2024 dollars
- **vote_average/vote_count:** TMDb's rating system for comparison with IMDb's averageRating/numVotes
- **genres/runtime:** Content characteristics for analyzing streaming vs theatrical patterns
- **cast/director:** Enable talent crossover analysis between distribution channels
- **release_year/release_date:** Temporal analysis and fuzzy matching keys
- **popularity:** TMDb-specific engagement metric not available in other datasets

In [3]:
# Load dataset
tmdb_movies_raw_df = pd.read_csv('data/raw/tmdb_movies_data.csv')

display_shape(tmdb_movies_raw_df)
display(tmdb_movies_raw_df.head())


Rows: 10,866
Columns: 21



id    imdb_id  popularity     budget     revenue  \
0  135397  tt0369610   32.985763  150000000  1513528810   
1   76341  tt1392190   28.419936  150000000   378436354   
2  262500  tt2908446   13.112507  110000000   295238201   
3  140607  tt2488496   11.173104  200000000  2068178225   
4  168259  tt2820852    9.335014  190000000  1506249360   

                 original_title  \
0                Jurassic World   
1            Mad Max: Fury Road   
2                     Insurgent   
3  Star Wars: The Force Awakens   
4                     Furious 7   

                                                cast  \
0  Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...   
1  Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...   
2  Shailene Woodley|Theo James|Kate Winslet|Ansel...   
3  Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...   
4  Vin Diesel|Paul Walker|Jason Statham|Michelle ...   

                                            homepage          director  \
0                      http://www.jurassicworld.com/   Colin Trevorrow   
1                        http://www.madmaxmovie.com/     George Miller   
2     http://www.thedivergentseries.movie/#insurgent  Robert Schwentke   
3  http://www.starwars.com/films/star-wars-episod...       J.J. Abrams   
4                           http://www.furious7.com/         James Wan   

                         tagline  ...  \
0              The park is open.  ...   
1             What a Lovely Day.  ...   
2     One Choice Can Destroy You  ...   
3  Every generation has a story.  ...   
4            Vengeance Hits Home  ...   

                                            overview runtime  \
0  Twenty-two years after the events of Jurassic ...     124   
1  An apocalyptic story set in the furthest reach...     120   
2  Beatrice Prior must confront her inner demons ...     119   
3  Thirty years after defeating the Galactic Empi...     136   
4  Deckard Shaw seeks revenge against Dominic Tor...     137   

                                      genres  \
0  Action|Adventure|Science Fiction|Thriller   
1  Action|Adventure|Science Fiction|Thriller   
2         Adventure|Science Fiction|Thriller   
3   Action|Adventure|Science Fiction|Fantasy   
4                      Action|Crime|Thriller   

                                production_companies release_date vote_count  \
0  Universal Studios|Amblin Entertainment|Legenda...       6/9/15       5562   
1  Village Roadshow Pictures|Kennedy Miller Produ...      5/13/15       6185   
2  Summit Entertainment|Mandeville Films|Red Wago...      3/18/15       2480   
3          Lucasfilm|Truenorth Productions|Bad Robot     12/15/15       5292   
4  Universal Pictures|Original Film|Media Rights ...       4/1/15       2947   

   vote_average  release_year    budget_adj   revenue_adj  
0           6.5          2015  1.379999e+08  1.392446e+09  
1           7.1          2015  1.379999e+08  3.481613e+08  
2           6.3          2015  1.012000e+08  2.716190e+08  
3           7.5          2015  1.839999e+08  1.902723e+09  
4           7.3          2015  1.747999e+08  1.385749e+09  

[5 rows x 21 columns]

#### IMDb Non-Commercial Datasets

IMDb provides free access to subsets of their data for non-commercial use, refreshed daily. This dataset extends the TMDb data with additional ratings and metadata, and provides validation for fuzzy matching when IMDb IDs are missing. IMDb's community-driven ratings represent a different audience demographic than TMDb, enabling comparison of rating systems.

Source URL: https://datasets.imdbws.com/

Type: TSV (Tab-Separated Values), gzip-compressed

Method: Programmatic download using Python httpx library

**Files Used:**

**title.basics.tsv.gz** - Core movie metadata
   - tconst (string) - IMDb unique identifier (e.g., tt0111161)
   - titleType (string) - Format type (movie, short, tvSeries, etc.)
   - primaryTitle (string) - Popular title used in marketing
   - originalTitle (string) - Original language title
   - isAdult (boolean) - Adult content flag (0 or 1)
   - startYear (YYYY) - Release year
   - runtimeMinutes (int) - Duration in minutes
   - genres (string array) - Up to three genres (comma-separated)

**title.ratings.tsv.gz** - Community ratings
   - tconst (string) - IMDb unique identifier
   - averageRating (float) - Weighted average rating (1-10 scale)
   - numVotes (int) - Total number of votes

**Why this dataset:**
IMDb's rating system is well-established and trusted, providing an alternative measure of audience reception. The tconst identifier enables precise linking to TMDb via imdb_id field, while the comprehensive coverage helps identify theatrical releases that may be missing from TMDb. The daily-updated nature ensures current data.

**Significance of variables:**
- **tconst/averageRating/numVotes:** Enable comparison of IMDb vs TMDb rating systems and vote engagement
- **titleType:** Filters dataset to movies only (excluding TV series, shorts)
- **startYear/runtimeMinutes:** Provide additional data points for movies missing this info in TMDb
- **genres:** Cross-validation of genre classifications across systems

>**title.basics.tsv.gz** - Core movie metadata

In [4]:
# Get files via URL download
URL = "https://datasets.imdbws.com/title.basics.tsv.gz"
LOCAL_FILE = "imdb_title_basics.tsv"

download_and_save_file(URL, LOCAL_FILE)

# Load dataset - note that this dataset is quite large at almost 1GB on disk
imdb_title_basics_raw_df = pd.read_csv(f'data/raw/{LOCAL_FILE}', sep='\t')

display_shape(imdb_title_basics_raw_df)
display(imdb_title_basics_raw_df.head())

data/raw/imdb_title_basics.tsv already exists. If you wish to re-download it, set download_if_exists=True

Rows: 12,116,115
Columns: 9



tconst titleType            primaryTitle           originalTitle  \
0  tt0000001     short              Carmencita              Carmencita   
1  tt0000002     short  Le clown et ses chiens  Le clown et ses chiens   
2  tt0000003     short            Poor Pierrot          Pauvre Pierrot   
3  tt0000004     short             Un bon bock             Un bon bock   
4  tt0000005     short        Blacksmith Scene        Blacksmith Scene   

   isAdult startYear endYear runtimeMinutes                    genres  
0        0      1894      \N              1         Documentary,Short  
1        0      1892      \N              5           Animation,Short  
2        0      1892      \N              5  Animation,Comedy,Romance  
3        0      1892      \N             12           Animation,Short  
4        0      1893      \N              1                     Short

>**title.ratings.tsv.gz** - Community ratings

In [5]:
# Get files via URL download
URL = "https://datasets.imdbws.com/title.ratings.tsv.gz"
LOCAL_FILE="imdb_title_ratings.tsv"

download_and_save_file(URL, LOCAL_FILE)

# Load dataset
imdb_title_ratings_raw_df = pd.read_csv(f'data/raw/{LOCAL_FILE}', sep='\t')

display_shape(imdb_title_ratings_raw_df)
display(imdb_title_ratings_raw_df.head())

data/raw/imdb_title_ratings.tsv already exists. If you wish to re-download it, set download_if_exists=True

Rows: 1,607,373
Columns: 3



tconst  averageRating  numVotes
0  tt0000001            5.7      2187
1  tt0000002            5.5       307
2  tt0000003            6.4      2273
3  tt0000004            5.2       196
4  tt0000005            6.2      3012

#### Streaming Platform Catalogs

Four major streaming platform datasets provide comprehensive coverage of content available on Netflix, Hulu, Disney+, and Amazon Prime as of mid-2021. These datasets enable identification of streaming-exclusive content (never released theatrically) versus theatrical films later added to streaming platforms. The consistent schema across platforms facilitates comparison of content strategies.

**Datasets:**
- Netflix: https://www.kaggle.com/datasets/shivamb/netflix-shows (~8K titles)
- Hulu: https://www.kaggle.com/datasets/shivamb/hulu-movies-and-tv-shows (~3K titles)  
- Disney+: https://www.kaggle.com/datasets/shivamb/disney-movies-and-tv-shows (~1.3K titles)
- Amazon Prime: https://www.kaggle.com/datasets/shivamb/amazon-prime-movies-and-tv-shows (~10K titles)

Type: CSV

Method: Manual download from Kaggle (all four datasets)

**Shared Schema:**
- show_id (string) - Unique identifier per platform
- type (string) - "Movie" or "TV Show"
- title (string) - Content title
- director (string) - Director name(s)
- cast (string) - Cast members (comma-separated)
- country (string) - Production country
- date_added (string) - Date added to platform (e.g., "September 25, 2021")
- release_year (int) - Original release year
- rating (string) - Content rating (PG-13, TV-MA, etc.)
- duration (string) - Runtime (e.g., "90 min" or "2 Seasons")
- listed_in (string) - Genres (comma-separated)
- description (string) - Synopsis

**Why these datasets:**
Streaming platforms represent the industry's future, but comprehensive availability data isn't accessible via APIs without commercial partnerships. These Kaggle datasets provide a snapshot of four major platforms' catalogs at a single point in time (2021), enabling analysis of platform content strategies. The lack of consistent identifiers (no TMDb/IMDb IDs) creates an authentic data wrangling challenge requiring fuzzy matching.

**Significance of variables:**
- **type:** Filters to movies only (excluding TV shows)
- **title/release_year:** Primary keys for fuzzy matching to theatrical databases
- **director/cast:** Enable cross-validation of matches and analysis of talent migration to streaming
- **date_added:** Indicates when content became available (may differ from release_year)
- **listed_in:** Genre analysis comparing streaming vs theatrical content preferences
- **duration:** Identifies potential data quality issues (TV shows mis-labeled as movies)

>**Amazon Prime**

In [6]:
# I decided to manually load these datasets into the project.
# Working with the kaggle and kagglehub Python packages is more trouble than it's worth.

amazon_prime_titles_raw_df = pd.read_csv('data/raw/amazon_prime_titles.csv')
display_shape(amazon_prime_titles_raw_df)
display(amazon_prime_titles_raw_df.head())


Rows: 9,668
Columns: 12



show_id   type                 title        director  \
0      s1  Movie   The Grand Seduction    Don McKellar   
1      s2  Movie  Take Care Good Night    Girish Joshi   
2      s3  Movie  Secrets of Deception     Josh Webber   
3      s4  Movie    Pink: Staying True  Sonia Anderson   
4      s5  Movie         Monster Maker    Giles Foster   

                                                cast         country  \
0     Brendan Gleeson, Taylor Kitsch, Gordon Pinsent          Canada   
1   Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar           India   
2  Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...   United States   
3  Interviews with: Pink, Adele, Beyoncé, Britney...   United States   
4  Harry Dean Stanton, Kieran O'Brien, George Cos...  United Kingdom   

       date_added  release_year rating duration                listed_in  \
0  March 30, 2021          2014    NaN  113 min            Comedy, Drama   
1  March 30, 2021          2018    13+  110 min     Drama, International   
2  March 30, 2021          2017    NaN   74 min  Action, Drama, Suspense   
3  March 30, 2021          2014    NaN   69 min              Documentary   
4  March 30, 2021          1989    NaN   45 min           Drama, Fantasy   

                                         description  
0  A small fishing village must procure a local d...  
1  A Metro Family decides to fight a Cyber Crimin...  
2  After a man discovers his wife is cheating on ...  
3  Pink breaks the mold once again, bringing her ...  
4  Teenage Matt Banting wants to work with a famo...

>**Disney Plus**

In [7]:
disney_plus_titles_raw_df = pd.read_csv('data/raw/disney_plus_titles.csv')
display_shape(disney_plus_titles_raw_df)
display(disney_plus_titles_raw_df.head())


Rows: 1,450
Columns: 12



show_id     type                                             title  \
0      s1    Movie  Duck the Halls: A Mickey Mouse Christmas Special   
1      s2    Movie                            Ernest Saves Christmas   
2      s3    Movie                      Ice Age: A Mammoth Christmas   
3      s4    Movie                        The Queen Family Singalong   
4      s5  TV Show                             The Beatles: Get Back   

                            director  \
0  Alonso Ramirez Ramos, Dave Wasson   
1                        John Cherry   
2                       Karen Disher   
3                    Hamish Hamilton   
4                                NaN   

                                                cast        country  \
0  Chris Diamantopoulos, Tony Anselmo, Tress MacN...            NaN   
1           Jim Varney, Noelle Parker, Douglas Seale            NaN   
2  Raymond Albert Romano, John Leguizamo, Denis L...  United States   
3  Darren Criss, Adam Lambert, Derek Hough, Alexa...            NaN   
4  John Lennon, Paul McCartney, George Harrison, ...            NaN   

          date_added  release_year rating  duration  \
0  November 26, 2021          2016   TV-G    23 min   
1  November 26, 2021          1988     PG    91 min   
2  November 26, 2021          2011   TV-G    23 min   
3  November 26, 2021          2021  TV-PG    41 min   
4  November 25, 2021          2021    NaN  1 Season   

                       listed_in  \
0              Animation, Family   
1                         Comedy   
2      Animation, Comedy, Family   
3                        Musical   
4  Docuseries, Historical, Music   

                                         description  
0   Join Mickey and the gang as they duck the halls!  
1  Santa Claus passes his magic bag to a new St. ...  
2          Sid the Sloth is on Santa's naughty list.  
3               This is real life, not just fantasy!  
4  A three-part documentary from Peter Jackson ca...

>**Hulu**

In [8]:
hulu_titles_raw_df = pd.read_csv('data/raw/hulu_titles.csv')
display_shape(hulu_titles_raw_df)
display(hulu_titles_raw_df.head())


Rows: 3,073
Columns: 12



show_id   type                           title director  cast country  \
0      s1  Movie  Ricky Velez: Here's Everything      NaN   NaN     NaN   
1      s2  Movie                    Silent Night      NaN   NaN     NaN   
2      s3  Movie                    The Marksman      NaN   NaN     NaN   
3      s4  Movie                            Gaia      NaN   NaN     NaN   
4      s5  Movie                        Settlers      NaN   NaN     NaN   

         date_added  release_year rating duration                  listed_in  \
0  October 24, 2021          2021  TV-MA      NaN           Comedy, Stand Up   
1  October 23, 2021          2020    NaN   94 min     Crime, Drama, Thriller   
2  October 23, 2021          2021  PG-13  108 min           Action, Thriller   
3  October 22, 2021          2021      R   97 min                     Horror   
4  October 22, 2021          2021    NaN  104 min  Science Fiction, Thriller   

                                         description  
0  ​Comedian Ricky Velez bares it all with his ho...  
1  Mark, a low end South London hitman recently r...  
2  A hardened Arizona rancher tries to protect an...  
3  A forest ranger and two survivalists with a cu...  
4  Mankind's earliest settlers on the Martian fro...

>**Netflix**

In [9]:
netflix_titles_raw_df = pd.read_csv('data/raw/netflix_titles.csv')
display_shape(netflix_titles_raw_df)
display(netflix_titles_raw_df.head())


Rows: 8,807
Columns: 12



show_id     type                  title         director  \
0      s1    Movie   Dick Johnson Is Dead  Kirsten Johnson   
1      s2  TV Show          Blood & Water              NaN   
2      s3  TV Show              Ganglands  Julien Leclercq   
3      s4  TV Show  Jailbirds New Orleans              NaN   
4      s5  TV Show           Kota Factory              NaN   

                                                cast        country  \
0                                                NaN  United States   
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa   
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN   
3                                                NaN            NaN   
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India   

           date_added  release_year rating   duration  \
0  September 25, 2021          2020  PG-13     90 min   
1  September 24, 2021          2021  TV-MA  2 Seasons   
2  September 24, 2021          2021  TV-MA   1 Season   
3  September 24, 2021          2021  TV-MA   1 Season   
4  September 24, 2021          2021  TV-MA  2 Seasons   

                                           listed_in  \
0                                      Documentaries   
1    International TV Shows, TV Dramas, TV Mysteries   
2  Crime TV Shows, International TV Shows, TV Act...   
3                             Docuseries, Reality TV   
4  International TV Shows, Romantic TV Shows, TV ...   

                                         description  
0  As her father nears the end of his life, filmm...  
1  After crossing paths at a party, a Cape Town t...  
2  To protect his family from a powerful drug lor...  
3  Feuds, flirtations and toilet talk go down amo...  
4  In a city of coaching centers known to train I...

#### Consumer Price Index (CPI) for Inflation Adjustment

The Federal Reserve Economic Data (FRED) provides historical Consumer Price Index data necessary for adjusting movie budgets and revenues to constant 2024 dollars. Without inflation adjustment, comparing a 1970s film budget to a 2020s budget is meaningless. The CPI-U (Consumer Price Index for All Urban Consumers) is the standard measure used by economists for this purpose.

Source URL: https://fred.stlouisfed.org/series/CPIAUCSL

Type: JSON (API response)

Method: API access via FRED API (programmatic)

**Dataset variables:**
- date (string) - Observation date (YYYY-MM-DD format)
- value (float) - CPI index value (1982-84 = 100 baseline)
- year (int) - Year extracted from date
- cpi (float) - Annual average CPI value

**Why this dataset:**
Inflation has been substantial over the 65-year span of this analysis (1960-2024). A \\$1 million budget in 1960 equals approximately \\$10.4 million in 2024 dollars. Without adjustment, financial analysis would be dominated by recency bias, making modern films appear far more expensive than historical films when they may actually be comparable in real terms. The FRED API provides authoritative, regularly-updated data from the U.S. Bureau of Labor Statistics.

**Significance of variables:**
- **year/cpi:** Used to calculate inflation multiplier: `adjusted_amount = original * (CPI_2024 / CPI_year)`
- **Annual averaging:** Smooths monthly volatility for more stable year-over-year comparisons

**Adjustment formula:**
```
budget_adj_2024 = budget_original × (CPI_2024 / CPI_release_year)
revenue_adj_2024 = revenue_original × (CPI_2024 / CPI_release_year)
```

In [10]:
def get_cpi_data(start_year=1960, end_year=2025, local_filename='cpi_data.json', path="data/raw", download_if_exists=False):
    """
    Get CPI data from FRED API
    CPI-U (Consumer Price Index for all Urban consumers)
    """
    
    filepath = f"{path}/{local_filename}"
    
    # Get cached data if we have it
    if os.path.exists(filepath) and download_if_exists is False:
        print(f"{filepath} already exists. If you wish to re-download it, set download_if_exists=True")
        return pd.read_json(filepath)
    
    url = 'https://api.stlouisfed.org/fred/series/observations'
    params = {
        'series_id': 'CPIAUCSL',
        'api_key': os.getenv('FRED_API'),
        'file_type': 'json',
        'observation_start': f'{start_year}-01-01',
        'observation_end': f'{end_year}-12-31',
        'frequency': 'a'
    }
    
    try:
        # Get the data as JSON
        response = httpx.get(url, params=params)
        response.raise_for_status()

        data = response.json()

        # Create dataframe
        cpi_df = pd.DataFrame(data['observations'])
        
        # Remove invalid data rows
        cpi_df = cpi_df[cpi_df['value'] != "."]
        
        # Transform data
        cpi_df['year'] = pd.to_datetime(cpi_df['date']).dt.year
        cpi_df['cpi'] = pd.to_numeric(cpi_df['value'])
        
        cpi_df = cpi_df[['year', 'cpi']]
        
        # Cache transformed data to disk
        cpi_df.to_json(filepath, orient='records')

        return cpi_df
        
    except httpx.HTTPStatusError as e:
        print(f"Error during request: {e}")
        
    except httpx.RequestError as e:
        print(f"An error occurred while requesting: {e}")

In [11]:
cpi_df = get_cpi_data()
display_shape(cpi_df)
display(cpi_df.head())
display(cpi_df['year'].unique())

data/raw/cpi_data.json already exists. If you wish to re-download it, set download_if_exists=True

Rows: 65
Columns: 2



year     cpi
0  1960  29.585
1  1961  29.902
2  1962  30.253
3  1963  30.633
4  1964  31.038

array([1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970,
       1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981,
       1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992,
       1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003,
       2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014,
       2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024])

## **2. Assess Data**

Before cleaning and merging the datasets, we must identify data quality and tidiness issues that could impact our analysis. This assessment phase follows a structured approach: each issue is evaluated both visually (inspecting sample data) and programmatically (using pandas methods to quantify the problem), with clear justifications for why each issue matters for our research questions.

This section documents the four most critical issues—two quality problems and two tidiness violations—that must be resolved before proceeding with the streaming vs theatrical analysis. Quality issues relate to the accuracy, completeness, and validity of individual data values (missing identifiers, incorrect null encodings, zero-value anomalies). Tidiness issues concern the structural organization of data (observational units split across tables, multiple values stored in single columns).

While these four issues represent the most significant barriers to analysis, additional data quality concerns will be identified and addressed during the cleaning phase. These include filtering datasets to relevant records (movies only, excluding TV shows), standardizing column names and data types, handling delimiter inconsistencies across platforms, and selecting the subset of variables needed for our specific research questions. The comprehensive cleaning strategy will be detailed in Section 3.

**Assessment approach:**
- **Visual assessment:** Display sample data using `.head()`, `.sample()`, or filtered subsets to observe patterns
- **Programmatic assessment:** Use pandas methods (`.isna()`, `.sum()`, `.duplicated()`, `.value_counts()`) to quantify issues
- **Justification:** Explain why each issue impacts the analysis and which data quality/tidiness principle it violates

### Quality Issue 1:

In [12]:
# Visual assessment
print("Sample of movies without IMDb IDs:")
tmdb_movies_raw_df[tmdb_movies_raw_df['imdb_id'].isna()][['id', 'original_title', 'release_year']].head(10)

Sample of movies without IMDb IDs:


id                                   original_title  release_year
548   355131                       Sense8: Creating the World          2015
997   287663             Star Wars Rebels: Spark of Rebellion          2014
1528   15257                               Hulk vs. Wolverine          2009
1750  101907                                    Hulk vs. Thor          2009
2401   45644  Opeth: In Live Concert At The Royal Albert Hall          2010
4797  369145                          Doctor Who: The Snowmen          2012
4872  269177                                      Party Bercy          2012
6071  279954                                 Portal: Survive!          2013
7527   50127                              Fallen: The Journey          2007
7809   50128                              Fallen: The Destiny          2007

In [13]:
# Programmatic assessment
def check_missing_imdb_ids(df):
    missing_imdb_ids = df['imdb_id'].isna().sum()
    total_movies = len(df)
    print(f"\nMissing IMDb IDs: {missing_imdb_ids} ({missing_imdb_ids/total_movies*100:.1f}%)")
    
check_missing_imdb_ids(tmdb_movies_raw_df)


Missing IMDb IDs: 10 (0.1%)


#### Issues and Justifications

The TMDb dataset exhibits a completeness quality issue with missing IMDb identifiers: 10 movies (0.1% of the dataset) lack `imdb_id` values.

Visual assessment reveals these missing IDs occur across various years (2007-2015) and include diverse content types from animated shorts ("Sense8: Creating the World") to concert films ("Opeth: In Live Concert") to TV-movie crossovers ("Hulk vs. Wolverine", "Doctor Who: The Snowmen").

This violates the completeness principle and directly impacts the project's primary merge strategy: these 10 movies cannot be linked to IMDb's rating data via the standard tconst-to-imdb_id join, resulting in incomplete rating comparisons. While the percentage is small, it demonstrates that not all theatrical releases receive IMDb coverage, and these gaps will require alternative matching strategies (fuzzy matching on title+year) if IMDb rating data is needed for these titles.

For the streaming comparison analysis, these movies may still provide value through TMDb-only metrics, but they cannot contribute to the IMDb vs TMDb rating system comparison.

### Quality Issue 2:

In [14]:
# Visual assessment
print("Sample of IMDb data with \\N values:")
imdb_title_basics_raw_df.head(20)

Sample of IMDb data with \N values:


tconst titleType                                 primaryTitle  \
0   tt0000001     short                                   Carmencita   
1   tt0000002     short                       Le clown et ses chiens   
2   tt0000003     short                                 Poor Pierrot   
3   tt0000004     short                                  Un bon bock   
4   tt0000005     short                             Blacksmith Scene   
5   tt0000006     short                            Chinese Opium Den   
6   tt0000007     short  Corbett and Courtney Before the Kinetograph   
7   tt0000008     short       Edison Kinetoscopic Record of a Sneeze   
8   tt0000009     movie                                   Miss Jerry   
9   tt0000010     short                          Leaving the Factory   
10  tt0000011     short                      Akrobatisches Potpourri   
11  tt0000012     short                       The Arrival of a Train   
12  tt0000013     short  The Photographical Congress Arrives in Lyon   
13  tt0000014     short                          The Waterer Watered   
14  tt0000015     short                               Around a Cabin   
15  tt0000016     short                        Boat Leaving the Port   
16  tt0000017     short                     Italienischer Bauerntanz   
17  tt0000018     short                         Das boxende Känguruh   
18  tt0000019     short                             The Clown Barber   
19  tt0000020     short                               The Derby 1895   

                                        originalTitle  isAdult startYear  \
0                                          Carmencita        0      1894   
1                              Le clown et ses chiens        0      1892   
2                                      Pauvre Pierrot        0      1892   
3                                         Un bon bock        0      1892   
4                                    Blacksmith Scene        0      1893   
5                                   Chinese Opium Den        0      1894   
6         Corbett and Courtney Before the Kinetograph        0      1894   
7              Edison Kinetoscopic Record of a Sneeze        0      1894   
8                                          Miss Jerry        0      1894   
9                 La sortie de l'usine Lumière à Lyon        0      1895   
10                            Akrobatisches Potpourri        0      1895   
11                   L'arrivée d'un train à La Ciotat        0      1896   
12  Le débarquement du congrès de photographie à Lyon        0      1895   
13                                  L'arroseur arrosé        0      1895   
14                                Autour d'une cabine        0      1894   
15                             Barque sortant du port        0      1895   
16                           Italienischer Bauerntanz        0      1895   
17                               Das boxende Känguruh        0      1895   
18                                   The Clown Barber        0      1898   
19                                     The Derby 1895        0      1895   

   endYear runtimeMinutes                    genres  
0       \N              1         Documentary,Short  
1       \N              5           Animation,Short  
2       \N              5  Animation,Comedy,Romance  
3       \N             12           Animation,Short  
4       \N              1                     Short  
5       \N              1                     Short  
6       \N              1               Short,Sport  
7       \N              1         Documentary,Short  
8       \N             45                   Romance  
9       \N              1         Documentary,Short  
10      \N              1         Documentary,Short  
11      \N              1         Documentary,Short  
12      \N              1         Documentary,Short  
13      \N              1              Comedy,Short  
14      \N              2    Animation,Comedy,Short  
15      \N              1        

In [15]:
# Programmatic assessment
def check_imdb_for_odd_null(df, name, columns=None):
    print(f"\nChecking for \\N null values in IMDb {name}:")
    
    if columns is None:
        columns = df.columns
    
    for col in columns:
        n_count = (df[col] == '\\N').sum()
        if n_count > 0:
            print(f"  {col}: {n_count:,} \\N values")
            
check_imdb_for_odd_null(imdb_title_basics_raw_df, "title basics")
check_imdb_for_odd_null(imdb_title_ratings_raw_df, "title ratings")


Checking for \N null values in IMDb title basics:
  startYear: 1,446,576 \N values
  endYear: 11,966,049 \N values
  runtimeMinutes: 7,801,758 \N values
  genres: 529,185 \N values

Checking for \N null values in IMDb title ratings:


#### Issues and Justifications

The IMDb datasets violate the completeness quality principle by using the string literal '\N' to represent missing values instead of proper null values. This appears throughout multiple columns including `startYear`, `endYear`, `runtimeMinutes`, and `genres`.

This encoding causes several data quality problems: (1) columns that should be numeric (like `runtimeMinutes` and `startYear`) are interpreted as object/string types due to the presence of '\N' text, preventing mathematical operations; (2) standard pandas null-handling methods like `isna()` and `fillna()` do not recognize '\N' as missing data; (3) these pseudo-nulls skew data type detection and require special handling in all analytical operations.

This is a validity issue that must be corrected by converting '\N' strings to proper pandas null values (np.nan or None) before any numeric operations, type conversions, or null-value analysis can be performed reliably. The issue affects approximately 10.5 million records in title.basics alone.

### Tidiness Issue 1:

In [16]:
# Visual assessment
print("IMDb Title Basics columns:", imdb_title_basics_raw_df.columns.tolist())
print("IMDb Ratings columns:", imdb_title_ratings_raw_df.columns.tolist())
print("\nBoth have 'tconst' - indicating they should be merged")

IMDb Title Basics columns: ['tconst', 'titleType', 'primaryTitle', 'originalTitle', 'isAdult', 'startYear', 'endYear', 'runtimeMinutes', 'genres']
IMDb Ratings columns: ['tconst', 'averageRating', 'numVotes']

Both have 'tconst' - indicating they should be merged


In [17]:
# Programmatic assessment
print(f"\nTitle Basics has {len(imdb_title_basics_raw_df):,} records")
print(f"Title Ratings has {len(imdb_title_ratings_raw_df):,} records")
print(f"Movies with ratings: {imdb_title_ratings_raw_df['tconst'].isin(imdb_title_basics_raw_df['tconst']).sum():,}")


Title Basics has 12,116,115 records
Title Ratings has 1,607,373 records
Movies with ratings: 1,607,367


#### Issues and Justifications

The IMDb movie data violates the tidiness principle that "each type of observational unit forms a table." Movies (identified by tconst) are split across two separate tables: *title.basics* contains descriptive metadata (title, year, runtime, genres), while *title.ratings* contains audience reception data (rating, vote count). Both tables describe the same observational unit (movies), meaning information about a single movie is unnecessarily fragmented.

This structure requires joining to access complete movie information and increases the risk of data inconsistency. The tables should be merged on the `tconst` key to create a single unified dataset where each row represents one complete movie observation with all relevant attributes in a single record.

### Tidiness Issue 2: 

In [18]:
# Visual assessment
print("Sample of pipe-delimited genres in TMDb:")
display(tmdb_movies_raw_df[['original_title', 'genres']].head())

Sample of pipe-delimited genres in TMDb:


original_title                                     genres
0                Jurassic World  Action|Adventure|Science Fiction|Thriller
1            Mad Max: Fury Road  Action|Adventure|Science Fiction|Thriller
2                     Insurgent         Adventure|Science Fiction|Thriller
3  Star Wars: The Force Awakens   Action|Adventure|Science Fiction|Fantasy
4                     Furious 7                      Action|Crime|Thriller

In [19]:
# Programmatic assessment
print(f"\nGenres column contains pipe-delimited values")
print(f"Example: {tmdb_movies_raw_df['genres'].iloc[0]}")


Genres column contains pipe-delimited values
Example: Action|Adventure|Science Fiction|Thriller


#### Issues and Justifications

The `genres` column in the TMDb dataset violates the tidiness principle that "each variable forms a column." Instead of storing genre as a single atomic value, the column contains pipe-delimited strings (e.g., "Action|Adventure|Science Fiction|Thriller") with multiple genre values concatenated in a single cell.

This structure prevents straightforward filtering, aggregation, and analysis by genre. For example, identifying all "Action" movies requires string parsing rather than simple column filtering. While splitting genres into separate rows would normalize the data structure, for this analysis we will keep genres as cleaned lists to maintain one-row-per-movie structure while ensuring the values are properly separated and accessible for analysis. This approach balances analytical flexibility with data structure simplicity.

## 3. Clean Data

This section systematically addresses the four critical data quality and tidiness issues identified during assessment, validates each cleaning operation, and prepares the datasets for merging. The cleaning process follows a methodical approach:

1. **Address Quality Issues:** Remove incomplete records and standardize null value encodings
2. **Resolve Tidiness Issues:** Merge fragmented tables and transform multi-value columns
3. **Dataset-Specific Cleaning:** Filter to relevant records (movies only), standardize data types, validate year fields
4. **Variable Selection:** Remove unnecessary columns to focus on analysis-relevant features
5. **Validation:** Verify each cleaning step with programmatic or visual confirmation

All cleaning operations include explicit justifications for methodology and clear validation of successful execution. The final combined dataset includes all variables needed to answer the research question: how streaming platforms compare to theatrical releases in financial performance, audience reception, and content characteristics across six decades.

In [20]:
# Make copy of TMDb dataframe
tmdb_movies_clean_df = tmdb_movies_raw_df.copy()

# Merge IMDb basic and ratngs dataframes into a new dataframe. We're only keeping movies with ratings
imdb_title_clean_df = pd.merge(imdb_title_basics_raw_df, imdb_title_ratings_raw_df, on='tconst', how='inner')

# Make copy of all streaming platform dataframes
amazon_prime_titles_clean_df = amazon_prime_titles_raw_df.copy()
disney_plus_titles_clean_df = disney_plus_titles_raw_df.copy()
hulu_titles_clean_df = hulu_titles_raw_df.copy()
netflix_titles_clean_df = netflix_titles_raw_df.copy()

# We won't be cleaning or modifying cpi_df so no need to make a copy of it

### Quality Issue 1: Missing IMDb IDs

In [21]:
# Get TMDb rows where we have an IMDb ID
tmdb_movies_clean_df = tmdb_movies_clean_df[tmdb_movies_clean_df['imdb_id'].notna()]

In [22]:
check_missing_imdb_ids(tmdb_movies_clean_df)


Missing IMDb IDs: 0 (0.0%)


#### Issues and Justifications

We filtered to keep only movies with valid IMDb IDs because:

1. IMDb IDs are essential for merging with IMDb ratings data
2. Only 10 movies (0.1%) lack IMDb IDs - negligible data loss
3. Alternative approaches (fuzzy matching by title/year) are complex and error-prone
4. These 10 movies would be excluded anyway during the merge operation

### Quality Issue 2: IMDb data with \N values

In [23]:
imdb_title_clean_df.replace('\\N', np.nan, inplace=True)

In [24]:
check_imdb_for_odd_null(imdb_title_clean_df, "title clean")


Checking for \N null values in IMDb title clean:


#### Issues and Justifications

We replaced IMDb's '\N' notation with pandas np.nan because:

1. '\N' is IMDb's text encoding for missing data, not a proper null value
2. Pandas requires np.nan for accurate null detection (.isnull(), .notna())
3. Proper nulls enable correct statistical calculations (mean, median ignore nulls)
4. This is standard practice when working with IMDb datasets
5. Allows pandas to handle missing data appropriately during merging

### Tidiness Issue 1: Merge two IMDb tables

In [25]:
# In lieu of making a copy and then merging the copies, we merged the raw datasets into a copy previously

In [26]:
# We can visualy see the averageRating and numVotes column added and the tables merged
imdb_title_clean_df.head()

tconst titleType            primaryTitle           originalTitle  \
0  tt0000001     short              Carmencita              Carmencita   
1  tt0000002     short  Le clown et ses chiens  Le clown et ses chiens   
2  tt0000003     short            Poor Pierrot          Pauvre Pierrot   
3  tt0000004     short             Un bon bock             Un bon bock   
4  tt0000005     short        Blacksmith Scene        Blacksmith Scene   

   isAdult startYear endYear runtimeMinutes                    genres  \
0        0      1894     NaN              1         Documentary,Short   
1        0      1892     NaN              5           Animation,Short   
2        0      1892     NaN              5  Animation,Comedy,Romance   
3        0      1892     NaN             12           Animation,Short   
4        0      1893     NaN              1                     Short   

   averageRating  numVotes  
0            5.7      2187  
1            5.5       307  
2            6.4      2273  
3            5.2       196  
4            6.2      3012

#### Issues and Justifications

We merged the two IMDb tables (title.basics + title.ratings) because:

1. Both tables describe the same observational unit (movies/titles)
2. Having movies split across tables violates the tidiness rule: "Each type of observational unit forms a table"
3. The tconst column serves as a unique identifier linking both tables
4. Inner join ensures we only retain movies with ratings (higher quality dataset)
5. Results in a single, complete table with both metadata and audience ratings

### Tidiness Issue 2: TMDb genres column

In [27]:
# Split pipe-delimited genres into Python tuples - was going to do lists but can't use drop_duplciates() with lists

a = imdb_title_clean_df.shape[0]
b = imdb_title_clean_df['genres'].apply(lambda x: isinstance(x, tuple)).sum().item()

def convert_genres_to_tuple(df, sep='|', inplace=False):   
    # Check if we've already converted genres to a tuple.
    # Happens if we run certain cells multiple times.
    df_rows = int(df.shape[0])
    df_num_genres_are_tuples = int(df['genres'].apply(lambda x: isinstance(x, tuple)).sum().item())
    
    if df_rows == df_num_genres_are_tuples:
        if inplace is True:
            return
        else:
            return df['genres']
    
    # Convert to tuple
    genres = df['genres'].fillna('').str.split(sep).apply(tuple)
            
    if inplace is True:
        df['genres'] = genres
    else:
        return genres

convert_genres_to_tuple(tmdb_movies_clean_df, inplace=True)

In [28]:
display(tmdb_movies_clean_df[['original_title', 'genres']].head())

original_title  \
0                Jurassic World   
1            Mad Max: Fury Road   
2                     Insurgent   
3  Star Wars: The Force Awakens   
4                     Furious 7   

                                           genres  
0  (Action, Adventure, Science Fiction, Thriller)  
1  (Action, Adventure, Science Fiction, Thriller)  
2          (Adventure, Science Fiction, Thriller)  
3   (Action, Adventure, Science Fiction, Fantasy)  
4                       (Action, Crime, Thriller)

#### Issues and Justifications

We split pipe-delimited genres into Python tuples because:

1. Pipe-delimited strings violate "each variable forms a column" - multiple values encoded in single cell
2. String format prevents programmatic analysis (filtering, counting, grouping by genre)
3. Python tuples are hashable, enabling use of drop_duplicates() and other pandas operations that require immutable values
4. Tuples maintain one-row-per-movie structure while providing iterable access to individual genres
5. Easy conversion to lists if mutability needed: list(genres_tuple)
6. Avoids data duplication that would occur with exploded rows (one row per genre)

### Remove Unnecessary Variables and Combine Datasets

Before merging the TMDb and IMDb datasets, we perform dataset-specific cleaning and variable selection. This process involves:

1. **TMDb Cleaning:**
   - Verify data integrity (check for zeros, duplicates, validate years)
   - Remove non-analytical columns (homepage, keywords, production companies)
   - Keep variables essential for streaming vs theatrical comparison

<p></p>

2. **IMDb Cleaning:**
   - Filter to movies only (exclude TV shows, shorts)
   - Convert string-encoded numbers to proper numeric types
   - Select only rating-related variables (tconst, averageRating, numVotes)

<p></p>

3. **Column Selection Rationale:**
   - Financial: budget, revenue (for performance comparison)
   - Audience: vote_average, vote_count (TMDb), averageRating, numVotes (IMDb)
   - Content: genres, runtime (for characteristic analysis)
   - Temporal: release_year (for time evolution analysis)
   - Identifiers: imdb_id, original_title (for merging and validation)

The goal is a streamlined dataset containing only the variables needed to address our research questions while eliminating noise from production metadata and internal IDs.

#### TMDb Data Quality Checks

We'll validate the cleaned TMDb dataset by checking for nulls and duplicates, examining the final schema, and confirming data types are correct for analysis.

In [29]:
# We're going to drop release_date from TMDb. Let's make sure we have all the release_year values first.

print(f"Null release_years: {tmdb_movies_clean_df['release_year'].isnull().sum()}")

# Extract year from release_date for comparison
tmdb_movies_clean_df['date_year'] = tmdb_movies_clean_df['release_date'].str.split('/').str[-1]

def transform_year(year_2digit):
    """
    Convert 2-digit year to 4-digit year.
    
    Assumes movies with year < 25 are from 2000s (2000-2024),
    and movies with year >= 25 are from 1900s (1925-1999).
    
    This cutoff is appropriate for a movie dataset spanning
    1960-2024, as no movies in the dataset would be from the 1920s.
    
    Args:
        year_2digit: Two-digit year as int or string
        
    Returns:
        Four-digit year as int
        
    Example:
        transform_year(15) -> 2015
        transform_year(95) -> 1995
    """
    year_2digit = int(year_2digit)
    
    if year_2digit < 25:
        return 2000 + year_2digit
    else:
        return 1900 + year_2digit

tmdb_movies_clean_df['date_year'] = tmdb_movies_clean_df['date_year'].apply(transform_year)

print(f"Null date_years: {tmdb_movies_clean_df['date_year'].isnull().sum()}")

print(f"\nMin date_year: {tmdb_movies_clean_df['date_year'].min()}")
print(f"Max date_year: {tmdb_movies_clean_df['date_year'].max()}")

print(f"\nMin release_year: {tmdb_movies_clean_df['release_year'].min()}")
print(f"Max release_year: {tmdb_movies_clean_df['release_year'].max()}")

# Compare release_year vs date_year
mismatches = tmdb_movies_clean_df[
    tmdb_movies_clean_df['release_year'] != tmdb_movies_clean_df['date_year']
]
print(f"\nYear mismatches: {len(mismatches)}")

# Show examples of mismatches if any
if len(mismatches) > 0:
    print("\nMismatch examples:")
    print(mismatches[['original_title', 'release_date', 'release_year', 'date_year']].head(10))

# Show distribution of differences
if len(mismatches) > 0:
    year_diff = mismatches['release_year'] - mismatches['date_year']
    print(f"\nYear difference stats:")
    print(year_diff.describe())

Null release_years: 0
Null date_years: 0

Min date_year: 1960
Max date_year: 2015

Min release_year: 1960
Max release_year: 2015

Year mismatches: 0


In [30]:
# Check for zero budgets/revenues
print(f"TMDb zero budgets: {(tmdb_movies_clean_df['budget'] == 0).sum()}")
print(f"TMDb zero revenues: {(tmdb_movies_clean_df['revenue'] == 0).sum()}")

# Convert zero budgets and revenues to NaN
tmdb_movies_clean_df['budget'] = tmdb_movies_clean_df['budget'].replace(0, np.nan)
tmdb_movies_clean_df['revenue'] = tmdb_movies_clean_df['revenue'].replace(0, np.nan)

# Validate
print(f"\nAfter conversion:")
print(f"Budget nulls: {tmdb_movies_clean_df['budget'].isna().sum():,}")
print(f"Revenue nulls: {tmdb_movies_clean_df['revenue'].isna().sum():,}")
print(f"Movies with both financial values: {tmdb_movies_clean_df[['budget', 'revenue']].notna().all(axis=1).sum():,}")

# Check for duplicate IMDb IDs
print(f"\nDuplicate imdb_ids in TMDb: {tmdb_movies_clean_df['imdb_id'].duplicated().sum()}")

# Check for zero runtimes
print(f"TMDb zero runtimes: {(tmdb_movies_clean_df['runtime'] == 0).sum()}")

TMDb zero budgets: 5687
TMDb zero revenues: 6006

After conversion:
Budget nulls: 5,687
Revenue nulls: 6,006
Movies with both financial values: 3,855

Duplicate imdb_ids in TMDb: 1
TMDb zero runtimes: 31


#### TMDb Cleaning

Here we'll drop duplicates and remove columns deemed non-critical for analysis.

In [31]:
tmdb_movies_clean_df.drop_duplicates(inplace=True)

tmdb_movies_clean_df.drop([
    'id', 'popularity', 'homepage', 'keywords', 'tagline', 'overview', 'production_companies', 
    'budget_adj', 'revenue_adj', 'cast', 'director', 'release_date', 'date_year'
], axis=1, inplace=True, errors='ignore')

#### TMDb Final View

In [32]:
print(f"\nDuplicate imdb_ids in TMDb: {tmdb_movies_clean_df['imdb_id'].duplicated().sum()}\n")
display(tmdb_movies_clean_df.head())
display(tmdb_movies_clean_df.info())


Duplicate imdb_ids in TMDb: 0



imdb_id       budget       revenue                original_title  \
0  tt0369610  150000000.0  1.513529e+09                Jurassic World   
1  tt1392190  150000000.0  3.784364e+08            Mad Max: Fury Road   
2  tt2908446  110000000.0  2.952382e+08                     Insurgent   
3  tt2488496  200000000.0  2.068178e+09  Star Wars: The Force Awakens   
4  tt2820852  190000000.0  1.506249e+09                     Furious 7   

   runtime                                          genres  vote_count  \
0      124  (Action, Adventure, Science Fiction, Thriller)        5562   
1      120  (Action, Adventure, Science Fiction, Thriller)        6185   
2      119          (Adventure, Science Fiction, Thriller)        2480   
3      136   (Action, Adventure, Science Fiction, Fantasy)        5292   
4      137                       (Action, Crime, Thriller)        2947   

   vote_average  release_year  
0           6.5          2015  
1           7.1          2015  
2           6.3          2015  
3           7.5          2015  
4           7.3          2015

<class 'pandas.core.frame.DataFrame'>
Index: 10855 entries, 0 to 10865
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   imdb_id         10855 non-null  object 
 1   budget          5168 non-null   float64
 2   revenue         4849 non-null   float64
 3   original_title  10855 non-null  object 
 4   runtime         10855 non-null  int64  
 5   genres          10855 non-null  object 
 6   vote_count      10855 non-null  int64  
 7   vote_average    10855 non-null  float64
 8   release_year    10855 non-null  int64  
dtypes: float64(3), int64(3), object(3)
memory usage: 848.0+ KB


None

#### IMDb Data Quality Checks

Examining the IMDb dataset for duplicates, null values, and non-numeric data in runtime fields. We'll also identify which columns to drop during cleanup.

In [33]:
imdb_columns = imdb_title_clean_df.columns

# Columns to drop and convert
drop_columns = ['isAdult']
numeric_columns = ['startYear', 'endyear', 'runtimeMinutes']

print(f"Duplicate tconsts in IMDb: {imdb_title_clean_df['tconst'].duplicated().sum()}")
print(f"IMDb zero runtimes: {(imdb_title_clean_df['runtimeMinutes'] == 0).sum()}")

display_shape(imdb_title_clean_df)

def check_null_column_values(df):
    print("Columns with NULL values:")
    for col in df.columns:
        n_count = (df[col].isnull()).sum()
        if n_count > 0:
            print(f"  {col}: {n_count:,} null values")
    print()

check_null_column_values(imdb_title_clean_df)
    
# Nearly all endYear values are null (1,538,909 / 1,607,367); drop column
drop_columns.append('endYear')

# Fill null numeric columns with zero
# Technically clean-up but we need to do this before the next check

for col in numeric_columns:
    if col in imdb_columns:
        imdb_title_clean_df[col].fillna(0, inplace=True)

check_null_column_values(imdb_title_clean_df)

# Check runtimeMinutes for non-numeric values
non_numeric_mask = pd.to_numeric(imdb_title_clean_df['runtimeMinutes'], errors='coerce').isnull()
non_numeric_rows = imdb_title_clean_df[non_numeric_mask]
non_numeric_row_count = non_numeric_rows.shape[0]

print(f"Found {non_numeric_row_count:,} rows where runtimeMinutes is not a numeric value:\n")
display(imdb_title_clean_df[non_numeric_mask])

print("\nUnique types:\n")
display(imdb_title_clean_df['titleType'].unique())

Duplicate tconsts in IMDb: 0
IMDb zero runtimes: 0

Rows: 1,607,367
Columns: 11

Columns with NULL values:
  primaryTitle: 1 null values
  originalTitle: 1 null values
  startYear: 255 null values
  endYear: 1,538,909 null values
  runtimeMinutes: 472,522 null values
  genres: 22,361 null values

Columns with NULL values:
  primaryTitle: 1 null values
  originalTitle: 1 null values
  endYear: 1,538,909 null values
  genres: 22,361 null values

Found 4 rows where runtimeMinutes is not a numeric value:



tconst  titleType  \
594683   tt12149332  tvEpisode   
1049604  tt27404292  tvEpisode   
1080033  tt28535095  tvEpisode   
1283807   tt3984412  tvEpisode   

                                              primaryTitle originalTitle  \
594683   Jeopardy! College Championship Semifinal Game ...             0   
1049604  Nord-Koreas röda prinsessa\tNord-Koreas röda p...             0   
1080033         I'm into Sharif Boys\tI'm into Sharif Boys             0   
1283807  I'm Not Going to Come Last, I'm Just Going to ...             0   

         isAdult startYear endYear        runtimeMinutes genres  \
594683      2020         0      45      Family,Game-Show    NaN   
1049604     2022         0     NaN           Documentary    NaN   
1080033     2023         0     NaN            Reality-TV    NaN   
1283807     2014         0     NaN  Game-Show,Reality-TV    NaN   

         averageRating  numVotes  
594683             6.9         9  
1049604            7.4         5  
1080033            2.8        46  
1283807            7.8         7


Unique types:



array(['short', 'movie', 'tvShort', 'tvEpisode', 'tvSeries', 'tvMovie',
       'tvMiniSeries', 'tvSpecial', 'video', 'videoGame'], dtype=object)

#### IMDb Cleanup

In this section, we'll convert data types (i.e. str to int), drop all rows that aren't movies, and remove non-critical columns.

In [34]:
# These rows are missing a bunch of data we want. Drop them.
imdb_title_clean_df = imdb_title_clean_df[~non_numeric_mask]

# Drop rows where titleType != 'movie'
imdb_title_clean_df = imdb_title_clean_df[imdb_title_clean_df['titleType'] == 'movie']

# Convert columns that should be numeric
for col in numeric_columns:
    if col in imdb_columns:
        imdb_title_clean_df[col] = pd.to_numeric(imdb_title_clean_df[col])

imdb_title_clean_df.drop(drop_columns, axis=1, inplace=True, errors='ignore')

# Convert genres to tuples to match TMBd format
convert_genres_to_tuple(imdb_title_clean_df, sep=",", inplace=True)

#### IMDb Final View

In [35]:
display(imdb_title_clean_df.head())
display(imdb_title_clean_df.info())

tconst titleType                   primaryTitle  \
8    tt0000009     movie                     Miss Jerry   
144  tt0000147     movie  The Corbett-Fitzsimmons Fight   
285  tt0000335     movie          Soldiers of the Cross   
383  tt0000502     movie                       Bohemios   
420  tt0000574     movie    The Story of the Kelly Gang   

                     originalTitle  startYear  runtimeMinutes  \
8                       Miss Jerry       1894              45   
144  The Corbett-Fitzsimmons Fight       1897             100   
285          Soldiers of the Cross       1900              40   
383                       Bohemios       1905             100   
420    The Story of the Kelly Gang       1906              70   

                             genres  averageRating  numVotes  
8                        (Romance,)            5.2       231  
144      (Documentary, News, Sport)            5.3       578  
285              (Biography, Drama)            5.5        64  
383                             (,)            3.1        25  
420  (Action, Adventure, Biography)            6.0      1039

<class 'pandas.core.frame.DataFrame'>
Index: 336033 entries, 8 to 1607326
Data columns (total 9 columns):
 #   Column          Non-Null Count   Dtype  
---  ------          --------------   -----  
 0   tconst          336033 non-null  object 
 1   titleType       336033 non-null  object 
 2   primaryTitle    336032 non-null  object 
 3   originalTitle   336032 non-null  object 
 4   startYear       336033 non-null  int64  
 5   runtimeMinutes  336033 non-null  int64  
 6   genres          336033 non-null  object 
 7   averageRating   336033 non-null  float64
 8   numVotes        336033 non-null  int64  
dtypes: float64(1), int64(3), object(5)
memory usage: 25.6+ MB


None

#### TMDb and IMDb Summary

In [36]:
# Final Validation Summary
print("=" * 80)
print("DATA CLEANING COMPLETE - SUMMARY")
print("=" * 80)

print("\nTMDB DATASET:")
print(f"   Rows: {len(tmdb_movies_clean_df):,}")
print(f"   Columns: {len(tmdb_movies_clean_df.columns)}")
print(f"   Column names: {', '.join(tmdb_movies_clean_df.columns.tolist())}")

print("\nIMDB DATASET:")
print(f"   Rows: {len(imdb_title_clean_df):,}")
print(f"   Columns: {len(imdb_title_clean_df.columns)}")
print(f"   Column names: {', '.join(imdb_title_clean_df.columns.tolist())}")

DATA CLEANING COMPLETE - SUMMARY

TMDB DATASET:
   Rows: 10,855
   Columns: 9
   Column names: imdb_id, budget, revenue, original_title, runtime, genres, vote_count, vote_average, release_year

IMDB DATASET:
   Rows: 336,033
   Columns: 9
   Column names: tconst, titleType, primaryTitle, originalTitle, startYear, runtimeMinutes, genres, averageRating, numVotes


#### TMDb and IMDb Merging

**Runtime Handling Strategy**

Based on the analysis above:

**Zero Runtimes:**
- Zero-minute runtimes are invalid for theatrical movies (even shorts have measurable runtime)
- These represent missing data incorrectly encoded as zeros
- **Decision:** Convert zeros to NaN for accurate statistical calculations

**Missing Runtime Strategy:**
After merging TMDb and IMDb, we will:
1. Use TMDb runtime as primary (more specific to theatrical releases)
2. Fill TMDb nulls with IMDb runtimeMinutes where available
3. Document remaining nulls for potential exclusion from runtime-based analyses

In [37]:
# Runtime Analysis - Check for zeros and missing values
print("RUNTIME CHECKS:\n")

# TMDb runtime analysis
tmdb_zero_runtime = (tmdb_movies_clean_df['runtime'] == 0).sum()
tmdb_null_runtime = tmdb_movies_clean_df['runtime'].isna().sum()
print(f"TMDb - Zero runtimes: {tmdb_zero_runtime:,}")
print(f"TMDb - Null runtimes: {tmdb_null_runtime:,}")
print(f"TMDb - Runtime range: {tmdb_movies_clean_df['runtime'].min()} - {tmdb_movies_clean_df['runtime'].max()}")

# IMDb runtime analysis
imdb_zero_runtime = (imdb_title_clean_df['runtimeMinutes'] == 0).sum()
imdb_null_runtime = imdb_title_clean_df['runtimeMinutes'].isna().sum()
print(f"\nIMDb - Zero runtimes: {imdb_zero_runtime:,}")
print(f"IMDb - Null runtimes: {imdb_null_runtime:,}")
print(f"IMDb - Runtime range: {imdb_title_clean_df['runtimeMinutes'].min()} - {imdb_title_clean_df['runtimeMinutes'].max()}")

RUNTIME CHECKS:

TMDb - Zero runtimes: 31
TMDb - Null runtimes: 0
TMDb - Runtime range: 0 - 900

IMDb - Zero runtimes: 33,067
IMDb - Null runtimes: 0
IMDb - Runtime range: 0 - 59460


In [38]:
# Convert zero runtimes to NaN in TMDb
tmdb_movies_clean_df['runtime'] = tmdb_movies_clean_df['runtime'].replace(0, np.nan)

# Validate the change
print(f"\nAfter conversion:")
print(f"TMDb - Null runtimes: {tmdb_movies_clean_df['runtime'].isna().sum():,}")


After conversion:
TMDb - Null runtimes: 31


---

**Genre Handling Strategy**

TMDb and IMDb use different but complementary genre systems:

**TMDb Genres:** More granular (e.g., "Science Fiction", "Adventure")
**IMDb Genres:** Includes additional categories (e.g., "Biography", "Film-Noir", "Musical")

**Key Differences**

- IMDb uses "Sci-Fi" vs TMDb's "Science Fiction"
- IMDb includes TV-specific genres (Game-Show, Reality-TV, Talk-Show, News)
- IMDb separates "Music" and "Musical"
- IMDb has "Biography" and "Film-Noir" which TMDb doesn't distinguish

**Merging Decision**

We'll merge genres from both sources to create a comprehensive genre classification:

1. **Normalize:** Map "Sci-Fi" to "Science Fiction" for consistency
2. **Filter:** Exclude TV-specific genres (Game-Show, News, Reality-TV, Talk-Show)
3. **Exclude:** Remove "Short" (it's a title type, not a genre)
4. **Preserve:** Keep valuable IMDb genres (Biography, Film-Noir, Musical, Sport)
5. **Deduplicate:** Combine into sorted tuple of unique genres

This approach maximizes genre coverage while maintaining data quality and consistency.

**Result:** Each movie has a comprehensive, normalized set of genres drawing from both authoritative sources, enabling robust content characteristic analysis.

In [39]:
# Quick check: What are the unique genres in each dataset?
def check_genres(df, name):
    df_genres = df['genres']
    
    # Extract unique genres from tuples
    unique_genres = set()
    for genre_tuple in df_genres.dropna():
        # Skip empty tuples
        if genre_tuple:
            unique_genres.update(genre_tuple)

    print(f"{name} unique genres ({len(unique_genres)}):")
    print(sorted(unique_genres))
    
    ## Check for empty string in genre and that it's the only value
    rows_no_genre = df_genres.apply(lambda x: '' in x and len(x) == 1).sum()
    print(f"\nRows in {name} with no genre: {rows_no_genre:,}\n")

    
check_genres(tmdb_movies_clean_df, "TMDb")
check_genres(imdb_title_clean_df, "IMDb")

TMDb unique genres (21):
['', 'Action', 'Adventure', 'Animation', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Family', 'Fantasy', 'Foreign', 'History', 'Horror', 'Music', 'Mystery', 'Romance', 'Science Fiction', 'TV Movie', 'Thriller', 'War', 'Western']

Rows in TMDb with no genre: 21

IMDb unique genres (29):
['', 'Action', 'Adult', 'Adventure', 'Animation', 'Biography', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Family', 'Fantasy', 'Film-Noir', 'Game-Show', 'History', 'Horror', 'Music', 'Musical', 'Mystery', 'News', 'Reality-TV', 'Romance', 'Sci-Fi', 'Short', 'Sport', 'Talk-Show', 'Thriller', 'War', 'Western']

Rows in IMDb with no genre: 10,833



In [40]:
# Drop IMDb rows with genres we don't want to analyze
exclude_genres = ['Adult', 'Game-Show', 'News', 'Reality-TV', 'Short', 'Talk-Show']
excluded_genres_mask = imdb_title_clean_df['genres'].apply(lambda x: any(val in x for val in exclude_genres))
imdb_title_clean_df.drop(imdb_title_clean_df[excluded_genres_mask].index, inplace=True)

# Function to replace a genre's value
def replace_genre(genre_tuple, target_str, replace_str):
    if target_str == replace_str:
        return genre_tuple
    
    genre_list = list(genre_tuple)
    
    if target_str in genre_list:
        index = genre_list.index(target_str)
        genre_list[index] = replace_str
        
    return tuple(genre_list)

# Normalize genres in IMDb
imdb_title_clean_df['genres'] = imdb_title_clean_df['genres'].apply(lambda g: replace_genre(g, 'Sci-Fi', 'Science Fiction'))
imdb_title_clean_df['genres'] = imdb_title_clean_df['genres'].apply(lambda g: replace_genre(g, 'Film-Noir', 'Film Noir'))

print(f"Rows with 'Musical' genre: {imdb_title_clean_df[imdb_title_clean_df['genres'].apply(lambda x: 'Musical' in x)].shape[0]:,}")
print(f"Rows with 'Music' genre: {imdb_title_clean_df[imdb_title_clean_df['genres'].apply(lambda x: 'Music' in x)].shape[0]:,}")
print(f"Rows with both genres: {imdb_title_clean_df[imdb_title_clean_df['genres'].apply(lambda x: 'Music' in x and 'Musical' in x)].shape[0]:,}")

# Since we have only movies, let's assume Music and Musical genres are the same
# "Phantom of the Opera" has the 'Music' genre but it is indeed a Musical.
imdb_title_clean_df['genres'] = imdb_title_clean_df['genres'].apply(lambda g: replace_genre(g, 'Music', 'Musical'))

# Check 'Sport' genre
print(f"\nRows with 'Sport' genre: {imdb_title_clean_df[imdb_title_clean_df['genres'].apply(lambda x: 'Sport' in x)].shape[0]:,}")
print(f"Rows with only 'Sport' genre: {imdb_title_clean_df[imdb_title_clean_df['genres'].apply(lambda x: 'Sport' in x and len(x) == 1)].shape[0]:,}")
# There are 254 rows where 'Sport' is the only genre. Spot checking them has mixed results.
# Keeping for now to see how they get merged into TMDb.

display_shape(imdb_title_clean_df)
check_genres(tmdb_movies_clean_df, "TMDb")
check_genres(imdb_title_clean_df, "IMDb")

Rows with 'Musical' genre: 6,975
Rows with 'Music' genre: 8,511
Rows with both genres: 190

Rows with 'Sport' genre: 4,253
Rows with only 'Sport' genre: 254

Rows: 330,560
Columns: 9

TMDb unique genres (21):
['', 'Action', 'Adventure', 'Animation', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Family', 'Fantasy', 'Foreign', 'History', 'Horror', 'Music', 'Mystery', 'Romance', 'Science Fiction', 'TV Movie', 'Thriller', 'War', 'Western']

Rows in TMDb with no genre: 21

IMDb unique genres (22):
['', 'Action', 'Adventure', 'Animation', 'Biography', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Family', 'Fantasy', 'Film Noir', 'History', 'Horror', 'Musical', 'Mystery', 'Romance', 'Science Fiction', 'Sport', 'Thriller', 'War', 'Western']

Rows in IMDb with no genre: 10,833



**Merge IMDb and TMDb Datasets**

Now we can do the actual merging of IMDb and TMDb to see where we stand.

In [41]:
merged_xmdb_df = pd.merge(
    tmdb_movies_clean_df, 
    imdb_title_clean_df, 
    left_on='imdb_id', 
    right_on='tconst', 
    how='left',
    suffixes=('_tmdb', '_imdb')
)

merged_xmdb_df.drop(columns=['imdb_id', 'tconst'], inplace=True, errors='ignore')

display(merged_xmdb_df.info())
print("\n")
display(merged_xmdb_df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10855 entries, 0 to 10854
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   budget          5168 non-null   float64
 1   revenue         4849 non-null   float64
 2   original_title  10855 non-null  object 
 3   runtime         10824 non-null  float64
 4   genres_tmdb     10855 non-null  object 
 5   vote_count      10855 non-null  int64  
 6   vote_average    10855 non-null  float64
 7   release_year    10855 non-null  int64  
 8   titleType       9459 non-null   object 
 9   primaryTitle    9459 non-null   object 
 10  originalTitle   9459 non-null   object 
 11  startYear       9459 non-null   float64
 12  runtimeMinutes  9459 non-null   float64
 13  genres_imdb     9459 non-null   object 
 14  averageRating   9459 non-null   float64
 15  numVotes        9459 non-null   float64
dtypes: float64(8), int64(2), object(6)
memory usage: 1.3+ MB


None

budget       revenue                original_title  runtime  \
0  150000000.0  1.513529e+09                Jurassic World    124.0   
1  150000000.0  3.784364e+08            Mad Max: Fury Road    120.0   
2  110000000.0  2.952382e+08                     Insurgent    119.0   
3  200000000.0  2.068178e+09  Star Wars: The Force Awakens    136.0   
4  190000000.0  1.506249e+09                     Furious 7    137.0   

                                      genres_tmdb  vote_count  vote_average  \
0  (Action, Adventure, Science Fiction, Thriller)        5562           6.5   
1  (Action, Adventure, Science Fiction, Thriller)        6185           7.1   
2          (Adventure, Science Fiction, Thriller)        2480           6.3   
3   (Action, Adventure, Science Fiction, Fantasy)        5292           7.5   
4                       (Action, Crime, Thriller)        2947           7.3   

   release_year titleType                                primaryTitle  \
0          2015     movie                              Jurassic World   
1          2015     movie                          Mad Max: Fury Road   
2          2015     movie             The Divergent Series: Insurgent   
3          2015     movie  Star Wars: Episode VII - The Force Awakens   
4          2015     movie                                   Furious 7   

                                originalTitle  startYear  runtimeMinutes  \
0                              Jurassic World     2015.0           124.0   
1                          Mad Max: Fury Road     2015.0           120.0   
2             The Divergent Series: Insurgent     2015.0           119.0   
3  Star Wars: Episode VII - The Force Awakens     2015.0           138.0   
4                            Fast & Furious 7     2015.0           137.0   

                            genres_imdb  averageRating   numVotes  
0  (Action, Adventure, Science Fiction)            6.9   718366.0  
1  (Action, Adventure, Science Fiction)            8.1  1189406.0  
2  (Action, Adventure, Science Fiction)            6.2   268250.0  
3  (Action, Adventure, Science Fiction)            7.7  1013886.0  
4                    (Action, Thriller)            7.1   434109.0

In [42]:
# Spot-check columns for nulls, zeros, empty tuples
def check_no_data(df, col):
    empty_string_rows = df[df[col] == ''].shape[0]
    null_rows = df[df[col].isnull()].shape[0]
    numeric_col_is_zero = 0
    
    if empty_string_rows > 0:
        print(f"Rows {col} empty string: {empty_string_rows:,}")
        
    if null_rows > 0:
        print(f"Rows {col} is null: {null_rows:,}")
        
    if is_numeric_dtype(df[col]):
        numeric_col_is_zero = df[df[col] == 0].shape[0]
        
        if numeric_col_is_zero > 0:
            print(f"Rows {col} is zero: {numeric_col_is_zero:,}")
            
    if col.startswith('genres'):
        rows_with_no_genres = df[df[col].str.len() == 0].shape[0]
        
        if rows_with_no_genres > 0:
            print(f"Rows {col} is empty: {rows_with_no_genres:,}")

for col in merged_xmdb_df.columns:
    check_no_data(merged_xmdb_df, col)

Rows budget is null: 5,687
Rows revenue is null: 6,006
Rows runtime is null: 31
Rows titleType is null: 1,396
Rows primaryTitle is null: 1,396
Rows originalTitle is null: 1,396
Rows startYear is null: 1,396
Rows runtimeMinutes is null: 1,396
Rows genres_imdb is null: 1,396
Rows averageRating is null: 1,396
Rows numVotes is null: 1,396


---

**Initial merged analysis**

- We have 1,396 rows that had no corresponding IMDb data
- We already knew budget and revenue had null data
- No numeric columns have zeros
- We have at least 1 genre in both genre columns except where there's no IMDb data

**Genre Merging**

Combining TMDb and IMDb genres to create comprehensive coverage. Both sources are normalized to use matching terminology (e.g., "Science Fiction" instead of "Sci-Fi"), and genres are deduplicated and sorted for consistency.

In [43]:
def merge_genres(row):
    """Merge IMDb and TMDb genre columns favoring TMDb when IMDb doesn't have any"""
    genres_tmdb = row['genres_tmdb']
    genres_imdb = row['genres_imdb']
    genres = None
    
    if isinstance(genres_imdb, tuple):
        genres = set(genres_tmdb + genres_imdb)
    else:
        genres = set(genres_tmdb)

    # If there's an empty string in the set and it's not the only element, then remove it
    # We'll deal with rows that have no genres later
    if '' in genres and len(genres) > 1:
        genres.remove('')

    return tuple(genres)

merged_xmdb_df['genres'] = merged_xmdb_df.apply(merge_genres, axis=1)
check_genres(merged_xmdb_df, "XMDb")

# IMDb filled in 9 of the TMDb rows with no genres, but we still have 12
genres_mask = merged_xmdb_df['genres'].apply(lambda x: '' in x and len(x) == 1)
display(merged_xmdb_df[genres_mask])

# No budget and revenue for these rows and some have either no runtime or very short runtimes
# Let's drop these
merged_xmdb_df.drop(merged_xmdb_df[genres_mask].index, inplace=True)

XMDb unique genres (24):
['', 'Action', 'Adventure', 'Animation', 'Biography', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Family', 'Fantasy', 'Foreign', 'History', 'Horror', 'Music', 'Musical', 'Mystery', 'Romance', 'Science Fiction', 'Sport', 'TV Movie', 'Thriller', 'War', 'Western']

Rows in XMDb with no genre: 12



budget  revenue                                     original_title  \
1709     NaN      NaN                                  Prayers for Bobby   
2365     NaN      NaN                                    Freshman Father   
2371     NaN      NaN                      Doctor Who: A Christmas Carol   
4541     NaN      NaN  London 2012 Olympic Opening Ceremony: Isles of...   
4882     NaN      NaN                         Cousin Ben Troop Screening   
5822     NaN      NaN                 Doctor Who: The Time of the Doctor   
5926     NaN      NaN                                       Prada: Candy   
6521     NaN      NaN                                        Saw Rebirth   
8603     NaN      NaN                         T2 3-D: Battle Across Time   
8867     NaN      NaN                    Mom's Got a Date With a Vampire   
9296     NaN      NaN                                          Goldeneye   
9788     NaN      NaN                                        The Amputee   

      runtime genres_tmdb  vote_count  vote_average  release_year titleType  \
1709     88.0         (,)          57           7.4          2009       NaN   
2365      NaN         (,)          12           5.8          2010       NaN   
2371     62.0         (,)          11           7.7          2010       NaN   
4541    220.0         (,)          12           8.3          2012       NaN   
4882      2.0         (,)          14           7.0          2012       NaN   
5822     60.0         (,)          26           8.5          2013       NaN   
5926      3.0         (,)          27           6.9          2013       NaN   
6521      6.0         (,)          24           5.9          2005       NaN   
8603     12.0         (,)          14           6.7          1996       NaN   
8867     85.0         (,)          16           5.4          2000       NaN   
9296    105.0         (,)          10           5.3          1989       NaN   
9788      5.0         (,)          11           5.0          1974       NaN   

     primaryTitle originalTitle  startYear  runtimeMinutes genres_imdb  \
1709          NaN           NaN        NaN             NaN         NaN   
2365          NaN           NaN        NaN             NaN         NaN   
2371          NaN           NaN        NaN             NaN         NaN   
4541          NaN           NaN        NaN             NaN         NaN   
4882          NaN           NaN        NaN             NaN         NaN   
5822          NaN           NaN        NaN             NaN         NaN   
5926          NaN           NaN        NaN             NaN         NaN   
6521          NaN           NaN        NaN             NaN         NaN   
8603          NaN           NaN        NaN             NaN         NaN   
8867          NaN           NaN        NaN             NaN         NaN   
9296          NaN           NaN        NaN             NaN         NaN   
9788          NaN           NaN        NaN             NaN         NaN   

      averageRating  numVotes genres  
1709            NaN       NaN    (,)  
2365            NaN       NaN    (,)  
2371            NaN       NaN    (,)  
4541            NaN       NaN    (,)  
4882            NaN       NaN    (,)  
5822            NaN       NaN    (,)  
5926            NaN       NaN    (,)  
6521            NaN       NaN    (,)  
8603            NaN       NaN    (,)  
8867            NaN       NaN    (,)  
9296            NaN       NaN    (,)  
9788            NaN       NaN    (,)

In [44]:
# Re-check what we have
display_shape(merged_xmdb_df)
check_genres(merged_xmdb_df, "XMDb")
display(merged_xmdb_df.head())


Rows: 10,843
Columns: 17

XMDb unique genres (23):
['Action', 'Adventure', 'Animation', 'Biography', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Family', 'Fantasy', 'Foreign', 'History', 'Horror', 'Music', 'Musical', 'Mystery', 'Romance', 'Science Fiction', 'Sport', 'TV Movie', 'Thriller', 'War', 'Western']

Rows in XMDb with no genre: 0



budget       revenue                original_title  runtime  \
0  150000000.0  1.513529e+09                Jurassic World    124.0   
1  150000000.0  3.784364e+08            Mad Max: Fury Road    120.0   
2  110000000.0  2.952382e+08                     Insurgent    119.0   
3  200000000.0  2.068178e+09  Star Wars: The Force Awakens    136.0   
4  190000000.0  1.506249e+09                     Furious 7    137.0   

                                      genres_tmdb  vote_count  vote_average  \
0  (Action, Adventure, Science Fiction, Thriller)        5562           6.5   
1  (Action, Adventure, Science Fiction, Thriller)        6185           7.1   
2          (Adventure, Science Fiction, Thriller)        2480           6.3   
3   (Action, Adventure, Science Fiction, Fantasy)        5292           7.5   
4                       (Action, Crime, Thriller)        2947           7.3   

   release_year titleType                                primaryTitle  \
0          2015     movie                              Jurassic World   
1          2015     movie                          Mad Max: Fury Road   
2          2015     movie             The Divergent Series: Insurgent   
3          2015     movie  Star Wars: Episode VII - The Force Awakens   
4          2015     movie                                   Furious 7   

                                originalTitle  startYear  runtimeMinutes  \
0                              Jurassic World     2015.0           124.0   
1                          Mad Max: Fury Road     2015.0           120.0   
2             The Divergent Series: Insurgent     2015.0           119.0   
3  Star Wars: Episode VII - The Force Awakens     2015.0           138.0   
4                            Fast & Furious 7     2015.0           137.0   

                            genres_imdb  averageRating   numVotes  \
0  (Action, Adventure, Science Fiction)            6.9   718366.0   
1  (Action, Adventure, Science Fiction)            8.1  1189406.0   
2  (Action, Adventure, Science Fiction)            6.2   268250.0   
3  (Action, Adventure, Science Fiction)            7.7  1013886.0   
4                    (Action, Thriller)            7.1   434109.0   

                                           genres  
0  (Science Fiction, Action, Adventure, Thriller)  
1  (Science Fiction, Action, Adventure, Thriller)  
2  (Action, Science Fiction, Adventure, Thriller)  
3   (Science Fiction, Action, Adventure, Fantasy)  
4                       (Action, Crime, Thriller)

In [45]:
# We can drop genres_tmdb and genres_imdb
merged_xmdb_df.drop(columns=['genres_tmdb', 'genres_imdb'], inplace=True, errors='ignore')

display_shape(merged_xmdb_df)
display(merged_xmdb_df.head())


Rows: 10,843
Columns: 15



budget       revenue                original_title  runtime  \
0  150000000.0  1.513529e+09                Jurassic World    124.0   
1  150000000.0  3.784364e+08            Mad Max: Fury Road    120.0   
2  110000000.0  2.952382e+08                     Insurgent    119.0   
3  200000000.0  2.068178e+09  Star Wars: The Force Awakens    136.0   
4  190000000.0  1.506249e+09                     Furious 7    137.0   

   vote_count  vote_average  release_year titleType  \
0        5562           6.5          2015     movie   
1        6185           7.1          2015     movie   
2        2480           6.3          2015     movie   
3        5292           7.5          2015     movie   
4        2947           7.3          2015     movie   

                                 primaryTitle  \
0                              Jurassic World   
1                          Mad Max: Fury Road   
2             The Divergent Series: Insurgent   
3  Star Wars: Episode VII - The Force Awakens   
4                                   Furious 7   

                                originalTitle  startYear  runtimeMinutes  \
0                              Jurassic World     2015.0           124.0   
1                          Mad Max: Fury Road     2015.0           120.0   
2             The Divergent Series: Insurgent     2015.0           119.0   
3  Star Wars: Episode VII - The Force Awakens     2015.0           138.0   
4                            Fast & Furious 7     2015.0           137.0   

   averageRating   numVotes                                          genres  
0            6.9   718366.0  (Science Fiction, Action, Adventure, Thriller)  
1            8.1  1189406.0  (Science Fiction, Action, Adventure, Thriller)  
2            6.2   268250.0  (Action, Science Fiction, Adventure, Thriller)  
3            7.7  1013886.0   (Science Fiction, Action, Adventure, Fantasy)  
4            7.1   434109.0                       (Action, Crime, Thriller)

In [46]:
# Fill TMDb NaN runtimes with IMDb values
merged_xmdb_df['runtime_final'] = merged_xmdb_df['runtime'].fillna(merged_xmdb_df['runtimeMinutes'])

# 8 rows with no runtime and most missing budget and revenue data
# Drop them
merged_xmdb_df.drop(merged_xmdb_df[merged_xmdb_df['runtime_final'].isnull()].index, inplace=True)

# Check agreement where both exist
both_exist = merged_xmdb_df[['runtime', 'runtimeMinutes']].notna().all(axis=1)

runtime_diff = abs(merged_xmdb_df.loc[both_exist, 'runtime'] - 
                  merged_xmdb_df.loc[both_exist, 'runtimeMinutes'])

print(f"Runtime differences - Median: {runtime_diff.median()}, Mean: {runtime_diff.mean():.2f}, Max: {runtime_diff.max():,}\n")

for i in range(0, int(runtime_diff.max()), 5):
    print(f"Number of rows with runtime_diff > {i}: {len(runtime_diff[runtime_diff > i].index):,}")

Runtime differences - Median: 0.0, Mean: 0.96, Max: 75.0

Number of rows with runtime_diff > 0: 2,161
Number of rows with runtime_diff > 5: 437
Number of rows with runtime_diff > 10: 158
Number of rows with runtime_diff > 15: 83
Number of rows with runtime_diff > 20: 38
Number of rows with runtime_diff > 25: 27
Number of rows with runtime_diff > 30: 20
Number of rows with runtime_diff > 35: 14
Number of rows with runtime_diff > 40: 11
Number of rows with runtime_diff > 45: 9
Number of rows with runtime_diff > 50: 7
Number of rows with runtime_diff > 55: 6
Number of rows with runtime_diff > 60: 5
Number of rows with runtime_diff > 65: 3
Number of rows with runtime_diff > 70: 2


---

**Runtime Reconciliation Decision**

**Analysis Results:**

- Median difference: 0.0 minutes (80% exact matches)
- Mean difference: 0.96 minutes  
- Only 1.5% of movies (158/10,855) differ by more than 10 minutes

**Decision:** Use TMDb runtime as primary, fill nulls with IMDb values

**Justification:**

1. TMDb is more specific to theatrical releases (our focus)
2. Excellent agreement between sources (median = 0) validates data quality
3. Small discrepancies (1-5 minutes) likely reflect:
   - Credits included/excluded
   - Different editions (theatrical vs extended)
   - Rounding conventions
4. Large discrepancies are rare (<2%) and won't significantly impact aggregate analyses

**Impact:**

- Before merge: 31 missing runtimes
- After merge: 8 missing runtimes (dropped due to insufficient data)
- Final dataset: 10,847 movies with reliable runtime data

In [47]:
# Quick validation of runtime_final
print("Runtime Coverage After Merge:")
print(f"Total movies: {len(merged_xmdb_df):,}")
print(f"Movies with runtime: {merged_xmdb_df['runtime_final'].notna().sum():,}")
print(f"Coverage: {(merged_xmdb_df['runtime_final'].notna().sum() / len(merged_xmdb_df) * 100):.1f}%")
print(f"\nRuntime Statistics:")
print(merged_xmdb_df['runtime_final'].describe())

Runtime Coverage After Merge:
Total movies: 10,835
Movies with runtime: 10,835
Coverage: 100.0%

Runtime Statistics:
count    10835.000000
mean       102.439686
std         30.812236
min          2.000000
25%         90.000000
50%         99.000000
75%        112.000000
max        900.000000
Name: runtime_final, dtype: float64


In [48]:
# Drop runtime and runtimeMinutes in favor of runtime_final
merged_xmdb_df.drop(columns=['runtime', 'runtimeMinutes'], inplace=True, errors='ignore')
merged_xmdb_df.rename(columns={'runtime_final': 'runtime'}, inplace=True)
merged_xmdb_df.head()

budget       revenue                original_title  vote_count  \
0  150000000.0  1.513529e+09                Jurassic World        5562   
1  150000000.0  3.784364e+08            Mad Max: Fury Road        6185   
2  110000000.0  2.952382e+08                     Insurgent        2480   
3  200000000.0  2.068178e+09  Star Wars: The Force Awakens        5292   
4  190000000.0  1.506249e+09                     Furious 7        2947   

   vote_average  release_year titleType  \
0           6.5          2015     movie   
1           7.1          2015     movie   
2           6.3          2015     movie   
3           7.5          2015     movie   
4           7.3          2015     movie   

                                 primaryTitle  \
0                              Jurassic World   
1                          Mad Max: Fury Road   
2             The Divergent Series: Insurgent   
3  Star Wars: Episode VII - The Force Awakens   
4                                   Furious 7   

                                originalTitle  startYear  averageRating  \
0                              Jurassic World     2015.0            6.9   
1                          Mad Max: Fury Road     2015.0            8.1   
2             The Divergent Series: Insurgent     2015.0            6.2   
3  Star Wars: Episode VII - The Force Awakens     2015.0            7.7   
4                            Fast & Furious 7     2015.0            7.1   

    numVotes                                          genres  runtime  
0   718366.0  (Science Fiction, Action, Adventure, Thriller)    124.0  
1  1189406.0  (Science Fiction, Action, Adventure, Thriller)    120.0  
2   268250.0  (Action, Science Fiction, Adventure, Thriller)    119.0  
3  1013886.0   (Science Fiction, Action, Adventure, Fantasy)    136.0  
4   434109.0                       (Action, Crime, Thriller)    137.0

In [49]:
# Check year agreement where both exist
both_have_year = merged_xmdb_df[['release_year', 'startYear']].notna().all(axis=1)

year_diff = abs(merged_xmdb_df.loc[both_have_year, 'release_year'] - 
                merged_xmdb_df.loc[both_have_year, 'startYear'])

print("Year Comparison Analysis")
print("=" * 70)
print(f"Total movies with both years: {both_have_year.sum():,}")
print(f"\nYear differences - Median: {year_diff.median()}, Mean: {year_diff.mean():.2f}, Max: {year_diff.max():.0f}\n")

# Distribution of differences
print("Distribution of year differences:")
for i in [0, 1, 2, 3, 5, 10, 15, 20]:
    count = (year_diff <= i).sum()
    pct = (count / len(year_diff) * 100)
    print(f"  Within {i} year(s): {count:,} movies ({pct:.1f}%)")

print(f"\nNumber of exact matches: {(year_diff == 0).sum():,}")

# Check for systematic bias (is one source consistently earlier/later?)
signed_diff = merged_xmdb_df.loc[both_have_year, 'release_year'] - merged_xmdb_df.loc[both_have_year, 'startYear']
print(f"\nSigned difference (TMDb - IMDb):")
print(f"  Mean: {signed_diff.mean():.2f}")
print(f"  TMDb later: {(signed_diff > 0).sum():,}")
print(f"  TMDb earlier: {(signed_diff < 0).sum():,}")
print(f"  Same year: {(signed_diff == 0).sum():,}")

Year Comparison Analysis
Total movies with both years: 9,459

Year differences - Median: 0.0, Mean: 0.03, Max: 5

Distribution of year differences:
  Within 0 year(s): 9,161 movies (96.8%)
  Within 1 year(s): 9,446 movies (99.9%)
  Within 2 year(s): 9,457 movies (100.0%)
  Within 3 year(s): 9,458 movies (100.0%)
  Within 5 year(s): 9,459 movies (100.0%)
  Within 10 year(s): 9,459 movies (100.0%)
  Within 15 year(s): 9,459 movies (100.0%)
  Within 20 year(s): 9,459 movies (100.0%)

Number of exact matches: 9,161

Signed difference (TMDb - IMDb):
  Mean: 0.02
  TMDb later: 255
  TMDb earlier: 43
  Same year: 9,161


---

**Analysis Results:**
- 96.8% exact matches between TMDb and IMDb years (9,161/9,459)
- Median difference: 0.0 years
- 99.9% within 1 year; 100% within 2 years
- No systematic bias (mean signed difference: +0.02 years)

**Decision:** Use TMDb `release_year` exclusively

**Justification:**

1. **Exceptional agreement:** 96.8% exact matches validates both sources
2. **Theatrical focus:** TMDb tracks wide theatrical release, aligning with financial analysis
3. **Complete coverage:** TMDb has 100% year coverage (10,855 movies)
4. **Minor discrepancies explained:** 298 movies (3.2%) differ by 1 year, likely due to:
   - International release timing (Dec→Jan cross-year releases)
   - Festival premiere vs wide release dates
   - Regional variations

**Implementation:** Keep `release_year`, drop `startYear` after validation.

In [50]:
merged_xmdb_df.drop(columns=['startYear'], inplace=True, errors='ignore')
merged_xmdb_df.head()

budget       revenue                original_title  vote_count  \
0  150000000.0  1.513529e+09                Jurassic World        5562   
1  150000000.0  3.784364e+08            Mad Max: Fury Road        6185   
2  110000000.0  2.952382e+08                     Insurgent        2480   
3  200000000.0  2.068178e+09  Star Wars: The Force Awakens        5292   
4  190000000.0  1.506249e+09                     Furious 7        2947   

   vote_average  release_year titleType  \
0           6.5          2015     movie   
1           7.1          2015     movie   
2           6.3          2015     movie   
3           7.5          2015     movie   
4           7.3          2015     movie   

                                 primaryTitle  \
0                              Jurassic World   
1                          Mad Max: Fury Road   
2             The Divergent Series: Insurgent   
3  Star Wars: Episode VII - The Force Awakens   
4                                   Furious 7   

                                originalTitle  averageRating   numVotes  \
0                              Jurassic World            6.9   718366.0   
1                          Mad Max: Fury Road            8.1  1189406.0   
2             The Divergent Series: Insurgent            6.2   268250.0   
3  Star Wars: Episode VII - The Force Awakens            7.7  1013886.0   
4                            Fast & Furious 7            7.1   434109.0   

                                           genres  runtime  
0  (Science Fiction, Action, Adventure, Thriller)    124.0  
1  (Science Fiction, Action, Adventure, Thriller)    120.0  
2  (Action, Science Fiction, Adventure, Thriller)    119.0  
3   (Science Fiction, Action, Adventure, Fantasy)    136.0  
4                       (Action, Crime, Thriller)    137.0

In [51]:
# Quick check on title columns. We already know they are the same entity as we merged on imdb_title = tconst
# No decisions to be made here, just informative analysis.
print("Title Matching Analysis")
print("=" * 70)

# Check 1: Do IMDb's two title fields match?
imdb_titles_match = (merged_xmdb_df['primaryTitle'] == merged_xmdb_df['originalTitle'])
print(f"IMDb primaryTitle == originalTitle: {imdb_titles_match.sum():,} / {len(merged_xmdb_df):,} ({imdb_titles_match.sum()/len(merged_xmdb_df)*100:.1f}%)")

# Check 2: TMDb vs IMDb original titles
tmdb_imdb_orig_match = (merged_xmdb_df['original_title'] == merged_xmdb_df['originalTitle'])
print(f"TMDb original_title == IMDb originalTitle: {tmdb_imdb_orig_match.sum():,} ({tmdb_imdb_orig_match.sum()/len(merged_xmdb_df)*100:.1f}%)")

# Check 3: TMDb vs IMDb primary title
tmdb_imdb_primary_match = (merged_xmdb_df['original_title'] == merged_xmdb_df['primaryTitle'])
print(f"TMDb original_title == IMDb primaryTitle: {tmdb_imdb_primary_match.sum():,} ({tmdb_imdb_primary_match.sum()/len(merged_xmdb_df)*100:.1f}%)")

# Find movies where NONE of the titles match
any_match = imdb_titles_match | tmdb_imdb_orig_match | tmdb_imdb_primary_match
no_match = ~any_match
print(f"\nMovies where NO titles match exactly: {no_match.sum():,} ({no_match.sum()/len(merged_xmdb_df)*100:.1f}%)")

# Show examples of non-matches
if no_match.sum() > 0:
    print("\nExample non-matching titles:")
    examples = merged_xmdb_df.loc[no_match, ['original_title', 'primaryTitle', 'originalTitle', 'release_year']].head(10)
    print(examples.to_string())

Title Matching Analysis
IMDb primaryTitle == originalTitle: 8,683 / 10,835 (80.1%)
TMDb original_title == IMDb originalTitle: 8,734 (80.6%)
TMDb original_title == IMDb primaryTitle: 8,503 (78.5%)

Movies where NO titles match exactly: 1,631 (15.1%)

Example non-matching titles:
                                                     original_title   primaryTitle                             originalTitle  release_year
100                                                    Frozen Fever            NaN                                       NaN          2015
116                              The Scorpion King: The Lost Throne            NaN                                       NaN          2015
140                             Dragonheart 3: The Sorcerer's Curse            NaN                                       NaN          2015
154                                        Il racconto dei racconti  Tale of Tales  Il racconto dei racconti - Tale of Tales          2015
159                       

---

**Title Column Selection**

Since we merged on IMDb IDs (authoritative matching), the title columns are redundant display metadata. We'll keep TMDb's `original_title` as the primary title field and drop IMDb's title variations.

In [52]:
merged_xmdb_df.drop(['primaryTitle', 'originalTitle', 'titleType'], axis=1, inplace=True, errors='ignore')

In [53]:
# Compare rating scales and vote counts
print("\nRatings Comparison:")
print("=" * 70)

# Check correlation between rating systems
corr = merged_xmdb_df[['vote_average', 'averageRating']].corr().iloc[0, 1]
print(f"Correlation between TMDb and IMDb ratings: {corr:.3f}")

# Descriptive stats
print("\nTMDb Ratings:")
print(merged_xmdb_df['vote_average'].describe())
print("\nIMDb Ratings:")
print(merged_xmdb_df['averageRating'].describe())

# Vote counts comparison
print("\nVote Counts:")
print(f"TMDb median votes: {merged_xmdb_df['vote_count'].median():,.0f}")
print(f"IMDb median votes: {merged_xmdb_df['numVotes'].median():,.0f}")

# Check for nulls
print(f"\nTMDb rating nulls: {merged_xmdb_df['vote_average'].isna().sum():,}")
print(f"IMDb rating nulls: {merged_xmdb_df['averageRating'].isna().sum():,}")


Ratings Comparison:
Correlation between TMDb and IMDb ratings: 0.845

TMDb Ratings:
count    10835.000000
mean         5.973503
std          0.934129
min          1.500000
25%          5.400000
50%          6.000000
75%          6.600000
max          9.200000
Name: vote_average, dtype: float64

IMDb Ratings:
count    9459.000000
mean        6.272915
std         1.037415
min         1.300000
25%         5.700000
50%         6.400000
75%         7.000000
max         9.300000
Name: averageRating, dtype: float64

Vote Counts:
TMDb median votes: 38
IMDb median votes: 21,019

TMDb rating nulls: 0
IMDb rating nulls: 1,376


In [54]:
# Rename columns for clarity
merged_xmdb_df.rename(columns={
    'vote_average': 'tmdb_rating',
    'vote_count': 'tmdb_votes',
    'averageRating': 'imdb_rating', 
    'numVotes': 'imdb_votes'
}, inplace=True)

# Create combined rating that we'll use in our main analysis
merged_xmdb_df['rating_combined'] = (
    merged_xmdb_df['tmdb_rating'] + merged_xmdb_df['imdb_rating']
) / 2

merged_xmdb_df.head()

budget       revenue                original_title  tmdb_votes  \
0  150000000.0  1.513529e+09                Jurassic World        5562   
1  150000000.0  3.784364e+08            Mad Max: Fury Road        6185   
2  110000000.0  2.952382e+08                     Insurgent        2480   
3  200000000.0  2.068178e+09  Star Wars: The Force Awakens        5292   
4  190000000.0  1.506249e+09                     Furious 7        2947   

   tmdb_rating  release_year  imdb_rating  imdb_votes  \
0          6.5          2015          6.9    718366.0   
1          7.1          2015          8.1   1189406.0   
2          6.3          2015          6.2    268250.0   
3          7.5          2015          7.7   1013886.0   
4          7.3          2015          7.1    434109.0   

                                           genres  runtime  rating_combined  
0  (Science Fiction, Action, Adventure, Thriller)    124.0             6.70  
1  (Science Fiction, Action, Adventure, Thriller)    120.0             7.60  
2  (Action, Science Fiction, Adventure, Thriller)    119.0             6.25  
3   (Science Fiction, Action, Adventure, Fantasy)    136.0             7.60  
4                       (Action, Crime, Thriller)    137.0             7.20

---

**Inflation Adjustment**

In [55]:
def adjust_for_inflation(amount, from_year, to_year=2024, cpi_df=None):
    """
    Adjust monetary value for inflation using CPI.
    
    Formula: adjusted_amount = original_amount * (CPI_to_year / CPI_from_year)
    """
    if pd.isna(amount) or amount == 0:
        return None
    
    try:
        from_cpi = cpi_df[cpi_df['year'] == from_year]['cpi'].iloc[0]
        to_cpi = cpi_df[cpi_df['year'] == to_year]['cpi'].iloc[0]
        
        adjusted = amount * (to_cpi / from_cpi)
        return round(adjusted, 2)
    
    except IndexError:
        # Year not in CPI data
        return None

def add_inflation_adjusted_colunns(df, cpi_df):
    """
    Add budget_adj_2024 and revenue_adj_2024 columns
    """
    df['budget_adj_2024'] = df.apply(
        lambda row: adjust_for_inflation(
            row['budget'],
            row['release_year'],
            to_year=2024,
            cpi_df=cpi_df
        ) if pd.notna(row['budget']) else None,
        axis=1
    )
 
    df['revenue_adj_2024'] = df.apply(
        lambda row: adjust_for_inflation(
            row['revenue'],
            row['release_year'],
            to_year=2024,
            cpi_df=cpi_df
        ) if pd.notna(row['revenue']) else None,
        axis=1
    )

    df['roi'] = ((df['revenue_adj_2024'] - df['budget_adj_2024']) / df['budget_adj_2024'] * 100)
    df['profit_margin'] = ((df['revenue_adj_2024'] - df['budget_adj_2024']) / df['revenue_adj_2024'] * 100)
    
    return df

In [56]:
add_inflation_adjusted_colunns(merged_xmdb_df, cpi_df)

budget       revenue                original_title  tmdb_votes  \
0      150000000.0  1.513529e+09                Jurassic World        5562   
1      150000000.0  3.784364e+08            Mad Max: Fury Road        6185   
2      110000000.0  2.952382e+08                     Insurgent        2480   
3      200000000.0  2.068178e+09  Star Wars: The Force Awakens        5292   
4      190000000.0  1.506249e+09                     Furious 7        2947   
...            ...           ...                           ...         ...   
10850          NaN           NaN            The Endless Summer          11   
10851          NaN           NaN                    Grand Prix          20   
10852          NaN           NaN           Beregis Avtomobilya          11   
10853          NaN           NaN        What's Up, Tiger Lily?          22   
10854      19000.0           NaN      Manos: The Hands of Fate          15   

       tmdb_rating  release_year  imdb_rating  imdb_votes  \
0              6.5          2015          6.9    718366.0   
1              7.1          2015          8.1   1189406.0   
2              6.3          2015          6.2    268250.0   
3              7.5          2015          7.7   1013886.0   
4              7.3          2015          7.1    434109.0   
...            ...           ...          ...         ...   
10850          7.4          1966          7.6      6748.0   
10851          5.7          1966          7.2     11755.0   
10852          6.5          1966          8.0      6580.0   
10853          5.4          1966          5.8     10312.0   
10854          1.5          1966          1.7     38330.0   

                                               genres  runtime  \
0      (Science Fiction, Action, Adventure, Thriller)    124.0   
1      (Science Fiction, Action, Adventure, Thriller)    120.0   
2      (Action, Science Fiction, Adventure, Thriller)    119.0   
3       (Science Fiction, Action, Adventure, Fantasy)    136.0   
4                           (Action, Crime, Thriller)    137.0   
...                                               ...      ...   
10850                            (Sport, Documentary)     95.0   
10851               (Drama, Sport, Action, Adventure)    176.0   
10852               (Romance, Crime, Comedy, Mystery)     94.0   
10853              (Crime, Action, Adventure, Comedy)     80.0   
10854                                       (Horror,)     74.0   

       rating_combined  budget_adj_2024  revenue_adj_2024         roi  \
0                 6.70     1.985414e+08      2.003320e+09  909.019207   
1                 7.60     1.985414e+08      5.009018e+08  152.290903   
2                 6.25     1.455970e+08      3.907800e+08  168.398365   
3                 7.60     2.647218e+08      2.737459e+09  934.089113   
4                 7.20     2.514857e+08      1.993685e+09  692.762821   
...                ...              ...               ...         ...   
10850             7.50              NaN               NaN         NaN   
10851             6.45              NaN               NaN         NaN   
10852             7.25              NaN               NaN         NaN   
10853             5.60              NaN               NaN         NaN   
10854             1.60     1.835565e+05               NaN         NaN   

       profit_margin  
0          90.089386  
1          60.363216  
2          62.741949  
3          90.329654  
4          87.385887  
...              ...  
10850            NaN  
10851            NaN  
10852            NaN  
10853            NaN  
10854            NaN  

[10835 rows x 15 columns]

---

**Final Cleaned Dataset Summary**

**Dataset Statistics:**
- Total movies: 10,835
- Columns: 11
- Date range: 1960-2015
- Complete coverage: runtime (100%), release_year (100%)
- Financial data: budget (47.7%), revenue (44.7%)
- Ratings: TMDb (100%), IMDb (87.3%)
- Genres: 24 unique genres (merged from both sources)

**Key Transformations Completed:**
1. Merged TMDb + IMDb on authoritative IDs
2. Normalized genres across sources
3. Reconciled runtimes (median difference: 0 minutes)
4. Validated release years (96.8% exact match)
5. Created combined rating metric
6. Removed redundant columns
7. Calculated inflation adjustment to 2024 dollars

**Dataset is ready for:**
- Storage
- Exploratory analysis

In [57]:
print("="*80)
print("SECTION 3 COMPLETE - DATA CLEANING VALIDATED")
print("="*80)
print(f"\nFinal dataset: {len(merged_xmdb_df):,} movies × {len(merged_xmdb_df.columns)} columns")
print(f"\nColumns: {', '.join(merged_xmdb_df.columns)}")
print(f"\nMemory usage: {merged_xmdb_df.memory_usage(deep=True).sum() / 1024**2:.1f} MB")

SECTION 3 COMPLETE - DATA CLEANING VALIDATED

Final dataset: 10,835 movies × 15 columns

Columns: budget, revenue, original_title, tmdb_votes, tmdb_rating, release_year, imdb_rating, imdb_votes, genres, runtime, rating_combined, budget_adj_2024, revenue_adj_2024, roi, profit_margin

Memory usage: 2.7 MB


## 4. Update your data store
Update your local database/data store with the cleaned data, following best practices for storing your cleaned data:

- Must maintain different instances / versions of data (raw and cleaned data)
- Must name the dataset files informatively
- Ensure both the raw and cleaned data is saved to your database/data store

In [ ]:
#FILL IN - saving data

## 5. Answer the research question

### **5.1:** Define and answer the research question 
Going back to the problem statement in step 1, use the cleaned data to answer the question you raised. Produce **at least** two visualizations using the cleaned data and explain how they help you answer the question.

*Research question:* FILL IN from answer to Step 1

In [ ]:
#Visual 1 - FILL IN

*Answer to research question:* FILL IN

In [ ]:
#Visual 2 - FILL IN

*Answer to research question:* FILL IN

### **5.2:** Reflection
In 2-4 sentences, if you had more time to complete the project, what actions would you take? For example, which data quality and structural issues would you look into further, and what research questions would you further explore?

*Answer:* FILL IN